class ExampleSentence {
  const ExampleSentence({
    required this.japanese,
    required this.hiragana,
    required this.romaji,
    required this.chinese,
  });

  final String japanese;
  final String hiragana;
  final String romaji;
  final String chinese;
}

ExampleSentence exampleSentenceFor(String kanji) {
  return _sentences[kanji]!;
}

const Map<String, ExampleSentence> _sentences = {
  "会う": ExampleSentence(
    japanese: "学生は先生に会う。",
    hiragana: "がくせいはせんせいにあう。",
    romaji: "gakusei wa sensei ni au.",
    chinese: "學生和老師見面。",
  ),
  "開ける": ExampleSentence(
    japanese: "学生はドアを開ける。",
    hiragana: "がくせいはドアをあける。",
    romaji: "gakusei wa doa o akeru.",
    chinese: "學生打開門。",
  ),
  "遊ぶ": ExampleSentence(
    japanese: "子供は公園で遊ぶ。",
    hiragana: "こどもはこうえんであそぶ。",
    romaji: "kodomo wa kouen de asobu.",
    chinese: "小孩在公園玩。",
  ),
  "浴びる": ExampleSentence(
    japanese: "子供は水を浴びる。",
    hiragana: "こどもはみずをあびる。",
    romaji: "kodomo wa mizu o abiru.",
    chinese: "小孩淋水。",
  ),
  "ある": ExampleSentence(
    japanese: "部屋に本がある。",
    hiragana: "へやにほんがある。",
    romaji: "heya ni hon ga aru.",
    chinese: "房間裡有書。",
  ),
  "歩く": ExampleSentence(
    japanese: "学生は道を歩く。",
    hiragana: "がくせいはみちをあるく。",
    romaji: "gakusei wa michi o aruku.",
    chinese: "學生走路。",
  ),
  "言う": ExampleSentence(
    japanese: "先生は言葉を言う。",
    hiragana: "せんせいはことばをいう。",
    romaji: "sensei wa kotoba o iu.",
    chinese: "老師說單字。",
  ),
  "行く": ExampleSentence(
    japanese: "学生は学校へ行く。",
    hiragana: "がくせいはがっこうへいく。",
    romaji: "gakusei wa gakkou e iku.",
    chinese: "學生去學校。",
  ),
  "急ぐ": ExampleSentence(
    japanese: "学生は駅へ急ぐ。",
    hiragana: "がくせいはえきへいそぐ。",
    romaji: "gakusei wa eki e isogu.",
    chinese: "學生趕去車站。",
  ),
  "いる": ExampleSentence(
    japanese: "教室に学生がいる。",
    hiragana: "きょうしつにがくせいがいる。",
    romaji: "kyoushitsu ni gakusei ga iru.",
    chinese: "教室裡有學生。",
  ),
  "歌う": ExampleSentence(
    japanese: "子供は歌を歌う。",
    hiragana: "こどもはうたをうたう。",
    romaji: "kodomo wa uta o utau.",
    chinese: "小孩唱歌。",
  ),
  "生まれる": ExampleSentence(
    japanese: "子供は家で生まれる。",
    hiragana: "こどもはいえでうまれる。",
    romaji: "kodomo wa ie de umareru.",
    chinese: "小孩在家出生。",
  ),
  "売る": ExampleSentence(
    japanese: "店は果物を売る。",
    hiragana: "みせはくだものをうる。",
    romaji: "mise wa kudamono o uru.",
    chinese: "商店賣水果。",
  ),
  "起きる": ExampleSentence(
    japanese: "学生は朝に起きる。",
    hiragana: "がくせいはあさにおきる。",
    romaji: "gakusei wa asa ni okiru.",
    chinese: "學生早晨起床。",
  ),
  "置く": ExampleSentence(
    japanese: "学生は本を机に置く。",
    hiragana: "がくせいはほんをつくえにおく。",
    romaji: "gakusei wa hon o tsukue ni oku.",
    chinese: "學生把書放在桌子上。",
  ),
  "送る": ExampleSentence(
    japanese: "母は子供に荷物を送る。",
    hiragana: "はははこどもににもつをおくる。",
    romaji: "haha wa kodomo ni nimotsu o okuru.",
    chinese: "母親送行李給小孩。",
  ),
  "教える": ExampleSentence(
    japanese: "先生は学生に漢字を教える。",
    hiragana: "せんせいはがくせいにかんじをおしえる。",
    romaji: "sensei wa gakusei ni kanji o oshieru.",
    chinese: "老師教學生漢字。",
  ),
  "押す": ExampleSentence(
    japanese: "学生はドアを押す。",
    hiragana: "がくせいはドアをおす。",
    romaji: "gakusei wa doa o osu.",
    chinese: "學生按門。",
  ),
  "覚える": ExampleSentence(
    japanese: "学生は言葉を覚える。",
    hiragana: "がくせいはことばをおぼえる。",
    romaji: "gakusei wa kotoba o oboeru.",
    chinese: "學生記住單字。",
  ),
  "終わる": ExampleSentence(
    japanese: "仕事が終わる。",
    hiragana: "しごとがおわる。",
    romaji: "shigoto ga owaru.",
    chinese: "工作結束。",
  ),
  "買う": ExampleSentence(
    japanese: "学生は本を買う。",
    hiragana: "がくせいはほんをかう。",
    romaji: "gakusei wa hon o kau.",
    chinese: "學生買書。",
  ),
  "返す": ExampleSentence(
    japanese: "学生は本を返す。",
    hiragana: "がくせいはほんをかえす。",
    romaji: "gakusei wa hon o kaesu.",
    chinese: "學生歸還書。",
  ),
  "帰る": ExampleSentence(
    japanese: "学生は家へ帰る。",
    hiragana: "がくせいはいえへかえる。",
    romaji: "gakusei wa ie e kaeru.",
    chinese: "學生回家。",
  ),
  "書く": ExampleSentence(
    japanese: "学生は漢字を書く。",
    hiragana: "がくせいはかんじをかく。",
    romaji: "gakusei wa kanji o kaku.",
    chinese: "學生寫漢字。",
  ),
  "貸す": ExampleSentence(
    japanese: "友達は学生に本を貸す。",
    hiragana: "ともだちはがくせいにほんをかす。",
    romaji: "tomodachi wa gakusei ni hon o kasu.",
    chinese: "朋友把書借給學生。",
  ),
  "借りる": ExampleSentence(
    japanese: "学生は友達に本を借りる。",
    hiragana: "がくせいはともだちにほんをかりる。",
    romaji: "gakusei wa tomodachi ni hon o kariru.",
    chinese: "學生向朋友借書。",
  ),
  "消える": ExampleSentence(
    japanese: "雪が消える。",
    hiragana: "ゆきがきえる。",
    romaji: "yuki ga kieru.",
    chinese: "雪消失。",
  ),
  "聞く": ExampleSentence(
    japanese: "学生は音楽を聞く。",
    hiragana: "がくせいはおんがくをきく。",
    romaji: "gakusei wa ongaku o kiku.",
    chinese: "學生聽音樂。",
  ),
  "切る": ExampleSentence(
    japanese: "母は野菜を切る。",
    hiragana: "はははやさいをきる。",
    romaji: "haha wa yasai o kiru.",
    chinese: "母親切蔬菜。",
  ),
  "着る": ExampleSentence(
    japanese: "子供は服を着る。",
    hiragana: "こどもはふくをきる。",
    romaji: "kodomo wa fuku o kiru.",
    chinese: "小孩穿衣服。",
  ),
  "来る": ExampleSentence(
    japanese: "友達は家へ来る。",
    hiragana: "ともだちはいえへくる。",
    romaji: "tomodachi wa ie e kuru.",
    chinese: "朋友來家。",
  ),
  "消す": ExampleSentence(
    japanese: "子供は絵を消す。",
    hiragana: "こどもはえをけす。",
    romaji: "kodomo wa e o kesu.",
    chinese: "小孩把圖畫擦掉。",
  ),
  "答える": ExampleSentence(
    japanese: "学生は質問に答える。",
    hiragana: "がくせいはしつもんにこたえる。",
    romaji: "gakusei wa shitsumon ni kotaeru.",
    chinese: "學生回答問題。",
  ),
  "困る": ExampleSentence(
    japanese: "学生は宿題に困る。",
    hiragana: "がくせいはしゅくだいにこまる。",
    romaji: "gakusei wa shukudai ni komaru.",
    chinese: "學生為作業所困擾。",
  ),
  "座る": ExampleSentence(
    japanese: "学生は椅子に座る。",
    hiragana: "がくせいはいすにすわる。",
    romaji: "gakusei wa isu ni suwaru.",
    chinese: "學生坐在椅子上。",
  ),
  "住む": ExampleSentence(
    japanese: "学生は家に住む。",
    hiragana: "がくせいはいえにすむ。",
    romaji: "gakusei wa ie ni sumu.",
    chinese: "學生住在家裡。",
  ),
  "出す": ExampleSentence(
    japanese: "学生は宿題を出す。",
    hiragana: "がくせいはしゅくだいをだす。",
    romaji: "gakusei wa shukudai o dasu.",
    chinese: "學生交出作業。",
  ),
  "立つ": ExampleSentence(
    japanese: "子供は道に立つ。",
    hiragana: "こどもはみちにたつ。",
    romaji: "kodomo wa michi ni tatsu.",
    chinese: "小孩站在路上。",
  ),
  "頼む": ExampleSentence(
    japanese: "子供は母に仕事を頼む。",
    hiragana: "こどもはははにしごとをたのむ。",
    romaji: "kodomo wa haha ni shigoto o tanomu.",
    chinese: "小孩拜託母親做事。",
  ),
  "食べる": ExampleSentence(
    japanese: "学生はご飯を食べる。",
    hiragana: "がくせいはごはんをたべる。",
    romaji: "gakusei wa gohan o taberu.",
    chinese: "學生吃飯。",
  ),
  "使う": ExampleSentence(
    japanese: "学生は辞書を使う。",
    hiragana: "がくせいはじしょをつかう。",
    romaji: "gakusei wa jisho o tsukau.",
    chinese: "學生使用字典。",
  ),
  "作る": ExampleSentence(
    japanese: "母はご飯を作る。",
    hiragana: "はははごはんをつくる。",
    romaji: "haha wa gohan o tsukuru.",
    chinese: "母親做飯。",
  ),
  "手伝う": ExampleSentence(
    japanese: "子供は母を手伝う。",
    hiragana: "こどもはははをてつだう。",
    romaji: "kodomo wa haha o tetsudau.",
    chinese: "小孩幫忙母親。",
  ),
  "出る": ExampleSentence(
    japanese: "学生は家を出る。",
    hiragana: "がくせいはいえをでる。",
    romaji: "gakusei wa ie o deru.",
    chinese: "學生離開家。",
  ),
  "撮る": ExampleSentence(
    japanese: "学生は写真を撮る。",
    hiragana: "がくせいはしゃしんをとる。",
    romaji: "gakusei wa shashin o toru.",
    chinese: "學生拍照。",
  ),
  "取る": ExampleSentence(
    japanese: "学生は荷物を取る。",
    hiragana: "がくせいはにもつをとる。",
    romaji: "gakusei wa nimotsu o toru.",
    chinese: "學生拿行李。",
  ),
  "飲む": ExampleSentence(
    japanese: "学生は水を飲む。",
    hiragana: "がくせいはみずをのむ。",
    romaji: "gakusei wa mizu o nomu.",
    chinese: "學生喝水。",
  ),
  "入る": ExampleSentence(
    japanese: "学生は部屋に入る。",
    hiragana: "がくせいはへやにはいる。",
    romaji: "gakusei wa heya ni hairu.",
    chinese: "學生進入房間。",
  ),
  "話す": ExampleSentence(
    japanese: "学生は友達と話す。",
    hiragana: "がくせいはともだちとはなす。",
    romaji: "gakusei wa tomodachi to hanasu.",
    chinese: "學生和朋友說話。",
  ),
  "待つ": ExampleSentence(
    japanese: "学生は駅で待つ。",
    hiragana: "がくせいはえきでまつ。",
    romaji: "gakusei wa eki de matsu.",
    chinese: "學生在車站等待。",
  ),
  "見る": ExampleSentence(
    japanese: "学生は映画を見る。",
    hiragana: "がくせいはえいがをみる。",
    romaji: "gakusei wa eiga o miru.",
    chinese: "學生看電影。",
  ),
  "読む": ExampleSentence(
    japanese: "学生は本を読む。",
    hiragana: "がくせいはほんをよむ。",
    romaji: "gakusei wa hon o yomu.",
    chinese: "學生讀書。",
  ),
  "大きい": ExampleSentence(
    japanese: "学校は大きい。",
    hiragana: "がっこうはおおきい。",
    romaji: "gakkou wa ookii.",
    chinese: "學校很大。",
  ),
  "小さい": ExampleSentence(
    japanese: "猫は小さい。",
    hiragana: "ねこはちいさい。",
    romaji: "neko wa chiisai.",
    chinese: "貓很小。",
  ),
  "高い": ExampleSentence(
    japanese: "山は高い。",
    hiragana: "やまはたかい。",
    romaji: "yama wa takai.",
    chinese: "山很高。",
  ),
  "安い": ExampleSentence(
    japanese: "本は安い。",
    hiragana: "ほんはやすい。",
    romaji: "hon wa yasui.",
    chinese: "書很便宜。",
  ),
  "新しい": ExampleSentence(
    japanese: "車は新しい。",
    hiragana: "くるまはあたらしい。",
    romaji: "kuruma wa atarashii.",
    chinese: "汽車是新的。",
  ),
  "古い": ExampleSentence(
    japanese: "家は古い。",
    hiragana: "いえはふるい。",
    romaji: "ie wa furui.",
    chinese: "家是舊的。",
  ),
  "良い": ExampleSentence(
    japanese: "天気は良い。",
    hiragana: "てんきはよい。",
    romaji: "tenki wa yoi.",
    chinese: "天氣很好。",
  ),
  "悪い": ExampleSentence(
    japanese: "天気は悪い。",
    hiragana: "てんきはわるい。",
    romaji: "tenki wa warui.",
    chinese: "天氣很壞。",
  ),
  "長い": ExampleSentence(
    japanese: "道は長い。",
    hiragana: "みちはながい。",
    romaji: "michi wa nagai.",
    chinese: "道路很長。",
  ),
  "短い": ExampleSentence(
    japanese: "名前は短い。",
    hiragana: "なまえはみじかい。",
    romaji: "namae wa mijikai.",
    chinese: "名字很短。",
  ),
  "多い": ExampleSentence(
    japanese: "人は多い。",
    hiragana: "ひとはおおい。",
    romaji: "hito wa ooi.",
    chinese: "人很多。",
  ),
  "少ない": ExampleSentence(
    japanese: "人は少ない。",
    hiragana: "ひとはすくない。",
    romaji: "hito wa sukunai.",
    chinese: "人很少。",
  ),
  "暑い": ExampleSentence(
    japanese: "夏は暑い。",
    hiragana: "なつはあつい。",
    romaji: "natsu wa atsui.",
    chinese: "夏天很炎熱。",
  ),
  "寒い": ExampleSentence(
    japanese: "冬は寒い。",
    hiragana: "ふゆはさむい。",
    romaji: "fuyu wa samui.",
    chinese: "冬天很寒冷。",
  ),
  "熱い": ExampleSentence(
    japanese: "お茶は熱い。",
    hiragana: "おちゃはあつい。",
    romaji: "ocha wa atsui.",
    chinese: "茶很熱。",
  ),
  "冷たい": ExampleSentence(
    japanese: "水は冷たい。",
    hiragana: "みずはつめたい。",
    romaji: "mizu wa tsumetai.",
    chinese: "水很冰冷。",
  ),
  "忙しい": ExampleSentence(
    japanese: "先生は忙しい。",
    hiragana: "せんせいはいそがしい。",
    romaji: "sensei wa isogashii.",
    chinese: "老師很忙碌。",
  ),
  "暇": ExampleSentence(
    japanese: "学生は暇です。",
    hiragana: "がくせいはひまです。",
    romaji: "gakusei wa hima desu.",
    chinese: "學生有空。",
  ),
  "難しい": ExampleSentence(
    japanese: "試験は難しい。",
    hiragana: "しけんはむずかしい。",
    romaji: "shiken wa muzukashii.",
    chinese: "考試很困難。",
  ),
  "易しい": ExampleSentence(
    japanese: "宿題は易しい。",
    hiragana: "しゅくだいはやさしい。",
    romaji: "shukudai wa yasashii.",
    chinese: "作業很容易。",
  ),
  "楽しい": ExampleSentence(
    japanese: "旅行は楽しい。",
    hiragana: "りょこうはたのしい。",
    romaji: "ryokou wa tanoshii.",
    chinese: "旅行很快樂。",
  ),
  "面白い": ExampleSentence(
    japanese: "映画は面白い。",
    hiragana: "えいがはおもしろい。",
    romaji: "eiga wa omoshiroi.",
    chinese: "電影很有趣。",
  ),
  "つまらない": ExampleSentence(
    japanese: "映画はつまらない。",
    hiragana: "えいがはつまらない。",
    romaji: "eiga wa tsumaranai.",
    chinese: "電影很無聊。",
  ),
  "明るい": ExampleSentence(
    japanese: "部屋は明るい。",
    hiragana: "へやはあかるい。",
    romaji: "heya wa akarui.",
    chinese: "房間很明亮。",
  ),
  "暗い": ExampleSentence(
    japanese: "夜は暗い。",
    hiragana: "よるはくらい。",
    romaji: "yoru wa kurai.",
    chinese: "晚上很昏暗。",
  ),
  "近い": ExampleSentence(
    japanese: "駅は近い。",
    hiragana: "えきはちかい。",
    romaji: "eki wa chikai.",
    chinese: "車站很近。",
  ),
  "遠い": ExampleSentence(
    japanese: "国は遠い。",
    hiragana: "くにはとおい。",
    romaji: "kuni wa tooi.",
    chinese: "國家很遠。",
  ),
  "早い": ExampleSentence(
    japanese: "朝は早い。",
    hiragana: "あさははやい。",
    romaji: "asa wa hayai.",
    chinese: "早晨很早。",
  ),
  "速い": ExampleSentence(
    japanese: "電車は速い。",
    hiragana: "でんしゃははやい。",
    romaji: "densha wa hayai.",
    chinese: "電車很快。",
  ),
  "遅い": ExampleSentence(
    japanese: "電車は遅い。",
    hiragana: "でんしゃはおそい。",
    romaji: "densha wa osoi.",
    chinese: "電車很慢。",
  ),
  "重い": ExampleSentence(
    japanese: "荷物は重い。",
    hiragana: "にもつはおもい。",
    romaji: "nimotsu wa omoi.",
    chinese: "行李很重。",
  ),
  "軽い": ExampleSentence(
    japanese: "鞄は軽い。",
    hiragana: "かばんはかるい。",
    romaji: "kaban wa karui.",
    chinese: "包包很輕。",
  ),
  "甘い": ExampleSentence(
    japanese: "果物は甘い。",
    hiragana: "くだものはあまい。",
    romaji: "kudamono wa amai.",
    chinese: "水果很甜。",
  ),
  "辛い": ExampleSentence(
    japanese: "肉は辛い。",
    hiragana: "にくはからい。",
    romaji: "niku wa karai.",
    chinese: "肉很辣。",
  ),
  "塩辛い": ExampleSentence(
    japanese: "魚は塩辛い。",
    hiragana: "さかなはしおからい。",
    romaji: "sakana wa shiokarai.",
    chinese: "魚很鹹。",
  ),
  "酸っぱい": ExampleSentence(
    japanese: "果物は酸っぱい。",
    hiragana: "くだものはすっぱい。",
    romaji: "kudamono wa suppai.",
    chinese: "水果很酸。",
  ),
  "美味しい": ExampleSentence(
    japanese: "ご飯は美味しい。",
    hiragana: "ごはんはおいしい。",
    romaji: "gohan wa oishii.",
    chinese: "飯很好吃。",
  ),
  "まずい": ExampleSentence(
    japanese: "食べ物はまずい。",
    hiragana: "たべものはまずい。",
    romaji: "tabemono wa mazui.",
    chinese: "食物很難吃。",
  ),
  "白い": ExampleSentence(
    japanese: "雪は白い。",
    hiragana: "ゆきはしろい。",
    romaji: "yuki wa shiroi.",
    chinese: "雪是白色的。",
  ),
  "黒い": ExampleSentence(
    japanese: "猫は黒い。",
    hiragana: "ねこはくろい。",
    romaji: "neko wa kuroi.",
    chinese: "貓是黑色的。",
  ),
  "赤い": ExampleSentence(
    japanese: "花は赤い。",
    hiragana: "はなはあかい。",
    romaji: "hana wa akai.",
    chinese: "花是紅色的。",
  ),
  "青い": ExampleSentence(
    japanese: "空は青い。",
    hiragana: "そらはあおい。",
    romaji: "sora wa aoi.",
    chinese: "天空是藍色的。",
  ),
  "若い": ExampleSentence(
    japanese: "学生は若い。",
    hiragana: "がくせいはわかい。",
    romaji: "gakusei wa wakai.",
    chinese: "學生很年輕。",
  ),
  "有名": ExampleSentence(
    japanese: "大学は有名です。",
    hiragana: "だいがくはゆうめいです。",
    romaji: "daigaku wa yuumei desu.",
    chinese: "大學很有名。",
  ),
  "元気": ExampleSentence(
    japanese: "子供は元気です。",
    hiragana: "こどもはげんきです。",
    romaji: "kodomo wa genki desu.",
    chinese: "小孩很有精神。",
  ),
  "親切": ExampleSentence(
    japanese: "先生は親切です。",
    hiragana: "せんせいはしんせつです。",
    romaji: "sensei wa shinsetsu desu.",
    chinese: "老師很親切。",
  ),
  "静か": ExampleSentence(
    japanese: "図書館は静かです。",
    hiragana: "としょかんはしずかです。",
    romaji: "toshokan wa shizuka desu.",
    chinese: "圖書館很安靜。",
  ),
  "賑やか": ExampleSentence(
    japanese: "市場は賑やかです。",
    hiragana: "いちばはにぎやかです。",
    romaji: "ichiba wa nigiyaka desu.",
    chinese: "市場很熱鬧。",
  ),
  "便利": ExampleSentence(
    japanese: "電車は便利です。",
    hiragana: "でんしゃはべんりです。",
    romaji: "densha wa benri desu.",
    chinese: "電車很方便。",
  ),
  "丈夫": ExampleSentence(
    japanese: "体は丈夫です。",
    hiragana: "からだはじょうぶです。",
    romaji: "karada wa joubu desu.",
    chinese: "身體很健康。",
  ),
  "先生": ExampleSentence(
    japanese: "先生は学校で教える。",
    hiragana: "せんせいはがっこうでおしえる。",
    romaji: "sensei wa gakkou de oshieru.",
    chinese: "老師在學校教。",
  ),
  "学生": ExampleSentence(
    japanese: "学生は本を読む。",
    hiragana: "がくせいはほんをよむ。",
    romaji: "gakusei wa hon o yomu.",
    chinese: "學生讀書。",
  ),
  "友達": ExampleSentence(
    japanese: "友達は家へ来る。",
    hiragana: "ともだちはいえへくる。",
    romaji: "tomodachi wa ie e kuru.",
    chinese: "朋友來家。",
  ),
  "子供": ExampleSentence(
    japanese: "子供は公園で遊ぶ。",
    hiragana: "こどもはこうえんであそぶ。",
    romaji: "kodomo wa kouen de asobu.",
    chinese: "小孩在公園玩。",
  ),
  "人": ExampleSentence(
    japanese: "人は部屋にいる。",
    hiragana: "ひとはへやにいる。",
    romaji: "hito wa heya ni iru.",
    chinese: "人在房間裡。",
  ),
  "男": ExampleSentence(
    japanese: "男は道を歩く。",
    hiragana: "おとこはみちをあるく。",
    romaji: "otoko wa michi o aruku.",
    chinese: "男人走路。",
  ),
  "女": ExampleSentence(
    japanese: "女は花を見る。",
    hiragana: "おんなははなをみる。",
    romaji: "onna wa hana o miru.",
    chinese: "女人看花。",
  ),
  "男の子": ExampleSentence(
    japanese: "男の子は公園で遊ぶ。",
    hiragana: "おとこのこはこうえんであそぶ。",
    romaji: "otokonoko wa kouen de asobu.",
    chinese: "男孩在公園玩。",
  ),
  "女の子": ExampleSentence(
    japanese: "女の子は歌を歌う。",
    hiragana: "おんなのこはうたをうたう。",
    romaji: "onnanoko wa uta o utau.",
    chinese: "女孩唱歌。",
  ),
  "父": ExampleSentence(
    japanese: "父は会社へ行く。",
    hiragana: "ちちはかいしゃへいく。",
    romaji: "chichi wa kaisha e iku.",
    chinese: "父親去公司。",
  ),
  "母": ExampleSentence(
    japanese: "母はご飯を作る。",
    hiragana: "はははごはんをつくる。",
    romaji: "haha wa gohan o tsukuru.",
    chinese: "母親做飯。",
  ),
  "兄": ExampleSentence(
    japanese: "兄は学生に本を貸す。",
    hiragana: "あにはがくせいにほんをかす。",
    romaji: "ani wa gakusei ni hon o kasu.",
    chinese: "哥哥把書借給學生。",
  ),
  "姉": ExampleSentence(
    japanese: "姉は歌を歌う。",
    hiragana: "あねはうたをうたう。",
    romaji: "ane wa uta o utau.",
    chinese: "姐姐唱歌。",
  ),
  "弟": ExampleSentence(
    japanese: "弟は水を飲む。",
    hiragana: "おとうとはみずをのむ。",
    romaji: "otouto wa mizu o nomu.",
    chinese: "弟弟喝水。",
  ),
  "妹": ExampleSentence(
    japanese: "妹は絵を見る。",
    hiragana: "いもうとはえをみる。",
    romaji: "imouto wa e o miru.",
    chinese: "妹妹看圖畫。",
  ),
  "医者": ExampleSentence(
    japanese: "医者は病院にいる。",
    hiragana: "いしゃはびょういんにいる。",
    romaji: "isha wa byouin ni iru.",
    chinese: "醫生在醫院。",
  ),
  "看護師": ExampleSentence(
    japanese: "看護師は病院にいる。",
    hiragana: "かんごしはびょういんにいる。",
    romaji: "kangoshi wa byouin ni iru.",
    chinese: "護士在醫院。",
  ),
  "学校": ExampleSentence(
    japanese: "学生は学校へ行く。",
    hiragana: "がくせいはがっこうへいく。",
    romaji: "gakusei wa gakkou e iku.",
    chinese: "學生去學校。",
  ),
  "家": ExampleSentence(
    japanese: "学生は家へ帰る。",
    hiragana: "がくせいはいえへかえる。",
    romaji: "gakusei wa ie e kaeru.",
    chinese: "學生回家。",
  ),
  "部屋": ExampleSentence(
    japanese: "学生は部屋に入る。",
    hiragana: "がくせいはへやにはいる。",
    romaji: "gakusei wa heya ni hairu.",
    chinese: "學生進入房間。",
  ),
  "駅": ExampleSentence(
    japanese: "学生は駅へ行く。",
    hiragana: "がくせいはえきへいく。",
    romaji: "gakusei wa eki e iku.",
    chinese: "學生去車站。",
  ),
  "銀行": ExampleSentence(
    japanese: "学生は銀行へ行く。",
    hiragana: "がくせいはぎんこうへいく。",
    romaji: "gakusei wa ginkou e iku.",
    chinese: "學生去銀行。",
  ),
  "病院": ExampleSentence(
    japanese: "学生は病院へ行く。",
    hiragana: "がくせいはびょういんへいく。",
    romaji: "gakusei wa byouin e iku.",
    chinese: "學生去醫院。",
  ),
  "会社": ExampleSentence(
    japanese: "父は会社へ行く。",
    hiragana: "ちちはかいしゃへいく。",
    romaji: "chichi wa kaisha e iku.",
    chinese: "父親去公司。",
  ),
  "店": ExampleSentence(
    japanese: "母は店へ行く。",
    hiragana: "はははみせへいく。",
    romaji: "haha wa mise e iku.",
    chinese: "母親去商店。",
  ),
  "郵便局": ExampleSentence(
    japanese: "学生は郵便局へ行く。",
    hiragana: "がくせいはゆうびんきょくへいく。",
    romaji: "gakusei wa yuubinkyoku e iku.",
    chinese: "學生去郵局。",
  ),
  "図書館": ExampleSentence(
    japanese: "学生は図書館へ行く。",
    hiragana: "がくせいはとしょかんへいく。",
    romaji: "gakusei wa toshokan e iku.",
    chinese: "學生去圖書館。",
  ),
  "公園": ExampleSentence(
    japanese: "子供は公園で遊ぶ。",
    hiragana: "こどもはこうえんであそぶ。",
    romaji: "kodomo wa kouen de asobu.",
    chinese: "小孩在公園玩。",
  ),
  "大学": ExampleSentence(
    japanese: "学生は大学へ行く。",
    hiragana: "がくせいはだいがくへいく。",
    romaji: "gakusei wa daigaku e iku.",
    chinese: "學生去大學。",
  ),
  "教室": ExampleSentence(
    japanese: "学生は教室に入る。",
    hiragana: "がくせいはきょうしつにはいる。",
    romaji: "gakusei wa kyoushitsu ni hairu.",
    chinese: "學生進入教室。",
  ),
  "空港": ExampleSentence(
    japanese: "学生は空港へ行く。",
    hiragana: "がくせいはくうこうへいく。",
    romaji: "gakusei wa kuukou e iku.",
    chinese: "學生去機場。",
  ),
  "海": ExampleSentence(
    japanese: "学生は海へ行く。",
    hiragana: "がくせいはうみへいく。",
    romaji: "gakusei wa umi e iku.",
    chinese: "學生去海洋。",
  ),
  "山": ExampleSentence(
    japanese: "学生は山へ行く。",
    hiragana: "がくせいはやまへいく。",
    romaji: "gakusei wa yama e iku.",
    chinese: "學生去山。",
  ),
  "川": ExampleSentence(
    japanese: "学生は川へ行く。",
    hiragana: "がくせいはかわへいく。",
    romaji: "gakusei wa kawa e iku.",
    chinese: "學生去河川。",
  ),
  "湖": ExampleSentence(
    japanese: "学生は湖へ行く。",
    hiragana: "がくせいはみずうみへいく。",
    romaji: "gakusei wa mizuumi e iku.",
    chinese: "學生去湖。",
  ),
  "森": ExampleSentence(
    japanese: "学生は森へ行く。",
    hiragana: "がくせいはもりへいく。",
    romaji: "gakusei wa mori e iku.",
    chinese: "學生去森林。",
  ),
  "ホテル": ExampleSentence(
    japanese: "学生はホテルへ行く。",
    hiragana: "がくせいはホテルへいく。",
    romaji: "gakusei wa hoteru e iku.",
    chinese: "學生去飯店。",
  ),
  "市場": ExampleSentence(
    japanese: "母は市場へ行く。",
    hiragana: "はははいちばへいく。",
    romaji: "haha wa ichiba e iku.",
    chinese: "母親去市場。",
  ),
  "川辺": ExampleSentence(
    japanese: "子供は川辺で遊ぶ。",
    hiragana: "こどもはかわべであそぶ。",
    romaji: "kodomo wa kawabe de asobu.",
    chinese: "小孩在河邊玩。",
  ),
  "場所": ExampleSentence(
    japanese: "公園は場所です。",
    hiragana: "こうえんはばしょです。",
    romaji: "kouen wa basho desu.",
    chinese: "公園是一個地方。",
  ),
  "本": ExampleSentence(
    japanese: "学生は本を読む。",
    hiragana: "がくせいはほんをよむ。",
    romaji: "gakusei wa hon o yomu.",
    chinese: "學生讀書。",
  ),
  "新聞": ExampleSentence(
    japanese: "学生は新聞を読む。",
    hiragana: "がくせいはしんぶんをよむ。",
    romaji: "gakusei wa shinbun o yomu.",
    chinese: "學生讀報紙。",
  ),
  "雑誌": ExampleSentence(
    japanese: "学生は雑誌を読む。",
    hiragana: "がくせいはざっしをよむ。",
    romaji: "gakusei wa zasshi o yomu.",
    chinese: "學生讀雜誌。",
  ),
  "辞書": ExampleSentence(
    japanese: "学生は辞書を使う。",
    hiragana: "がくせいはじしょをつかう。",
    romaji: "gakusei wa jisho o tsukau.",
    chinese: "學生使用字典。",
  ),
  "机": ExampleSentence(
    japanese: "学生は本を机に置く。",
    hiragana: "がくせいはほんをつくえにおく。",
    romaji: "gakusei wa hon o tsukue ni oku.",
    chinese: "學生把書放在桌子上。",
  ),
  "椅子": ExampleSentence(
    japanese: "学生は椅子に座る。",
    hiragana: "がくせいはいすにすわる。",
    romaji: "gakusei wa isu ni suwaru.",
    chinese: "學生坐在椅子上。",
  ),
  "時計": ExampleSentence(
    japanese: "学生は時計を見る。",
    hiragana: "がくせいはとけいをみる。",
    romaji: "gakusei wa tokei o miru.",
    chinese: "學生看時鐘。",
  ),
  "電話": ExampleSentence(
    japanese: "学生は電話を使う。",
    hiragana: "がくせいはでんわをつかう。",
    romaji: "gakusei wa denwa o tsukau.",
    chinese: "學生使用電話。",
  ),
  "携帯": ExampleSentence(
    japanese: "学生は携帯を使う。",
    hiragana: "がくせいはけいたいをつかう。",
    romaji: "gakusei wa keitai o tsukau.",
    chinese: "學生使用手機。",
  ),
  "車": ExampleSentence(
    japanese: "学生は車で行く。",
    hiragana: "がくせいはくるまでいく。",
    romaji: "gakusei wa kuruma de iku.",
    chinese: "學生坐汽車去。",
  ),
  "電車": ExampleSentence(
    japanese: "学生は電車で行く。",
    hiragana: "がくせいはでんしゃでいく。",
    romaji: "gakusei wa densha de iku.",
    chinese: "學生坐電車去。",
  ),
  "飛行機": ExampleSentence(
    japanese: "学生は飛行機で行く。",
    hiragana: "がくせいはひこうきでいく。",
    romaji: "gakusei wa hikouki de iku.",
    chinese: "學生坐飛機去。",
  ),
  "船": ExampleSentence(
    japanese: "学生は船で行く。",
    hiragana: "がくせいはふねでいく。",
    romaji: "gakusei wa fune de iku.",
    chinese: "學生坐船去。",
  ),
  "自転車": ExampleSentence(
    japanese: "学生は自転車で行く。",
    hiragana: "がくせいはじてんしゃでいく。",
    romaji: "gakusei wa jitensha de iku.",
    chinese: "學生騎腳踏車去。",
  ),
  "道": ExampleSentence(
    japanese: "学生は道を歩く。",
    hiragana: "がくせいはみちをあるく。",
    romaji: "gakusei wa michi o aruku.",
    chinese: "學生走路。",
  ),
  "窓": ExampleSentence(
    japanese: "学生は窓を開ける。",
    hiragana: "がくせいはまどをあける。",
    romaji: "gakusei wa mado o akeru.",
    chinese: "學生打開窗戶。",
  ),
  "ドア": ExampleSentence(
    japanese: "学生はドアを開ける。",
    hiragana: "がくせいはドアをあける。",
    romaji: "gakusei wa doa o akeru.",
    chinese: "學生打開門。",
  ),
  "鍵": ExampleSentence(
    japanese: "学生は鍵を使う。",
    hiragana: "がくせいはかぎをつかう。",
    romaji: "gakusei wa kagi o tsukau.",
    chinese: "學生使用鑰匙。",
  ),
  "傘": ExampleSentence(
    japanese: "学生は傘を使う。",
    hiragana: "がくせいはかさをつかう。",
    romaji: "gakusei wa kasa o tsukau.",
    chinese: "學生使用雨傘。",
  ),
  "靴": ExampleSentence(
    japanese: "学生は靴を買う。",
    hiragana: "がくせいはくつをかう。",
    romaji: "gakusei wa kutsu o kau.",
    chinese: "學生買鞋子。",
  ),
  "服": ExampleSentence(
    japanese: "子供は服を着る。",
    hiragana: "こどもはふくをきる。",
    romaji: "kodomo wa fuku o kiru.",
    chinese: "小孩穿衣服。",
  ),
  "帽子": ExampleSentence(
    japanese: "子供は帽子を買う。",
    hiragana: "こどもはぼうしをかう。",
    romaji: "kodomo wa boushi o kau.",
    chinese: "小孩買帽子。",
  ),
  "鞄": ExampleSentence(
    japanese: "学生は鞄を使う。",
    hiragana: "がくせいはかばんをつかう。",
    romaji: "gakusei wa kaban o tsukau.",
    chinese: "學生使用包包。",
  ),
  "財布": ExampleSentence(
    japanese: "学生は財布を使う。",
    hiragana: "がくせいはさいふをつかう。",
    romaji: "gakusei wa saifu o tsukau.",
    chinese: "學生使用錢包。",
  ),
  "お金": ExampleSentence(
    japanese: "学生はお金を使う。",
    hiragana: "がくせいはおかねをつかう。",
    romaji: "gakusei wa okane o tsukau.",
    chinese: "學生使用金錢。",
  ),
  "切符": ExampleSentence(
    japanese: "学生は切符を買う。",
    hiragana: "がくせいはきっぷをかう。",
    romaji: "gakusei wa kippu o kau.",
    chinese: "學生買車票。",
  ),
  "食べ物": ExampleSentence(
    japanese: "学生は食べ物を食べる。",
    hiragana: "がくせいはたべものをたべる。",
    romaji: "gakusei wa tabemono o taberu.",
    chinese: "學生吃食物。",
  ),
  "ご飯": ExampleSentence(
    japanese: "学生はご飯を食べる。",
    hiragana: "がくせいはごはんをたべる。",
    romaji: "gakusei wa gohan o taberu.",
    chinese: "學生吃飯。",
  ),
  "朝ご飯": ExampleSentence(
    japanese: "学生は朝ご飯を食べる。",
    hiragana: "がくせいはあさごはんをたべる。",
    romaji: "gakusei wa asagohan o taberu.",
    chinese: "學生吃早餐。",
  ),
  "昼ご飯": ExampleSentence(
    japanese: "学生は昼ご飯を食べる。",
    hiragana: "がくせいはひるごはんをたべる。",
    romaji: "gakusei wa hirugohan o taberu.",
    chinese: "學生吃午餐。",
  ),
  "晩ご飯": ExampleSentence(
    japanese: "学生は晩ご飯を食べる。",
    hiragana: "がくせいはばんごはんをたべる。",
    romaji: "gakusei wa bangohan o taberu.",
    chinese: "學生吃晚餐。",
  ),
  "果物": ExampleSentence(
    japanese: "学生は果物を食べる。",
    hiragana: "がくせいはくだものをたべる。",
    romaji: "gakusei wa kudamono o taberu.",
    chinese: "學生吃水果。",
  ),
  "野菜": ExampleSentence(
    japanese: "学生は野菜を食べる。",
    hiragana: "がくせいはやさいをたべる。",
    romaji: "gakusei wa yasai o taberu.",
    chinese: "學生吃蔬菜。",
  ),
  "肉": ExampleSentence(
    japanese: "学生は肉を食べる。",
    hiragana: "がくせいはにくをたべる。",
    romaji: "gakusei wa niku o taberu.",
    chinese: "學生吃肉。",
  ),
  "魚": ExampleSentence(
    japanese: "学生は魚を食べる。",
    hiragana: "がくせいはさかなをたべる。",
    romaji: "gakusei wa sakana o taberu.",
    chinese: "學生吃魚。",
  ),
  "卵": ExampleSentence(
    japanese: "学生は卵を食べる。",
    hiragana: "がくせいはたまごをたべる。",
    romaji: "gakusei wa tamago o taberu.",
    chinese: "學生吃雞蛋。",
  ),
  "飲み物": ExampleSentence(
    japanese: "学生は飲み物を飲む。",
    hiragana: "がくせいはのみものをのむ。",
    romaji: "gakusei wa nomimono o nomu.",
    chinese: "學生喝飲料。",
  ),
  "水": ExampleSentence(
    japanese: "学生は水を飲む。",
    hiragana: "がくせいはみずをのむ。",
    romaji: "gakusei wa mizu o nomu.",
    chinese: "學生喝水。",
  ),
  "お茶": ExampleSentence(
    japanese: "学生はお茶を飲む。",
    hiragana: "がくせいはおちゃをのむ。",
    romaji: "gakusei wa ocha o nomu.",
    chinese: "學生喝茶。",
  ),
  "牛乳": ExampleSentence(
    japanese: "学生は牛乳を飲む。",
    hiragana: "がくせいはぎゅうにゅうをのむ。",
    romaji: "gakusei wa gyuunyuu o nomu.",
    chinese: "學生喝牛奶。",
  ),
  "犬": ExampleSentence(
    japanese: "犬は家にいる。",
    hiragana: "いぬはいえにいる。",
    romaji: "inu wa ie ni iru.",
    chinese: "狗在家裡。",
  ),
  "猫": ExampleSentence(
    japanese: "猫は家にいる。",
    hiragana: "ねこはいえにいる。",
    romaji: "neko wa ie ni iru.",
    chinese: "貓在家裡。",
  ),
  "鳥": ExampleSentence(
    japanese: "鳥は空にいる。",
    hiragana: "とりはそらにいる。",
    romaji: "tori wa sora ni iru.",
    chinese: "鳥在天空。",
  ),
  "花": ExampleSentence(
    japanese: "子供は花を見る。",
    hiragana: "こどもははなをみる。",
    romaji: "kodomo wa hana o miru.",
    chinese: "小孩看花。",
  ),
  "木": ExampleSentence(
    japanese: "木は大きい。",
    hiragana: "きはおおきい。",
    romaji: "ki wa ookii.",
    chinese: "樹木很大。",
  ),
  "石": ExampleSentence(
    japanese: "子供は石を取る。",
    hiragana: "こどもはいしをとる。",
    romaji: "kodomo wa ishi o toru.",
    chinese: "小孩拿石頭。",
  ),
  "空": ExampleSentence(
    japanese: "空は青い。",
    hiragana: "そらはあおい。",
    romaji: "sora wa aoi.",
    chinese: "天空是藍色的。",
  ),
  "天気": ExampleSentence(
    japanese: "天気は良い。",
    hiragana: "てんきはよい。",
    romaji: "tenki wa yoi.",
    chinese: "天氣很好。",
  ),
  "雨": ExampleSentence(
    japanese: "今日は雨です。",
    hiragana: "きょうはあめです。",
    romaji: "kyou wa ame desu.",
    chinese: "今天下雨。",
  ),
  "雪": ExampleSentence(
    japanese: "今日は雪です。",
    hiragana: "きょうはゆきです。",
    romaji: "kyou wa yuki desu.",
    chinese: "今天下雪。",
  ),
  "風": ExampleSentence(
    japanese: "今日は風です。",
    hiragana: "きょうはかぜです。",
    romaji: "kyou wa kaze desu.",
    chinese: "今天有風。",
  ),
  "春": ExampleSentence(
    japanese: "春は良い。",
    hiragana: "はるはよい。",
    romaji: "haru wa yoi.",
    chinese: "春天很好。",
  ),
  "夏": ExampleSentence(
    japanese: "夏は暑い。",
    hiragana: "なつはあつい。",
    romaji: "natsu wa atsui.",
    chinese: "夏天很炎熱。",
  ),
  "秋": ExampleSentence(
    japanese: "秋は良い。",
    hiragana: "あきはよい。",
    romaji: "aki wa yoi.",
    chinese: "秋天很好。",
  ),
  "冬": ExampleSentence(
    japanese: "冬は寒い。",
    hiragana: "ふゆはさむい。",
    romaji: "fuyu wa samui.",
    chinese: "冬天很寒冷。",
  ),
  "朝": ExampleSentence(
    japanese: "学生は朝に起きる。",
    hiragana: "がくせいはあさにおきる。",
    romaji: "gakusei wa asa ni okiru.",
    chinese: "學生早晨起床。",
  ),
  "昼": ExampleSentence(
    japanese: "学生は昼にご飯を食べる。",
    hiragana: "がくせいはひるにごはんをたべる。",
    romaji: "gakusei wa hiru ni gohan o taberu.",
    chinese: "學生中午吃飯。",
  ),
  "夜": ExampleSentence(
    japanese: "学生は夜に本を読む。",
    hiragana: "がくせいはよるにほんをよむ。",
    romaji: "gakusei wa yoru ni hon o yomu.",
    chinese: "學生晚上讀書。",
  ),
  "時間": ExampleSentence(
    japanese: "時間は長い。",
    hiragana: "じかんはながい。",
    romaji: "jikan wa nagai.",
    chinese: "時間很長。",
  ),
  "分": ExampleSentence(
    japanese: "時間は分です。",
    hiragana: "じかんはふんです。",
    romaji: "jikan wa fun desu.",
    chinese: "時間是分鐘。",
  ),
  "秒": ExampleSentence(
    japanese: "時間は秒です。",
    hiragana: "じかんはびょうです。",
    romaji: "jikan wa byou desu.",
    chinese: "時間是秒。",
  ),
  "今日": ExampleSentence(
    japanese: "学生は今日本を読む。",
    hiragana: "がくせいはきょうほんをよむ。",
    romaji: "gakusei wa kyou hon o yomu.",
    chinese: "學生今天讀書。",
  ),
  "昨日": ExampleSentence(
    japanese: "昨日は休みです。",
    hiragana: "きのうはやすみです。",
    romaji: "kinou wa yasumi desu.",
    chinese: "昨天休假。",
  ),
  "明日": ExampleSentence(
    japanese: "学生は明日学校へ行く。",
    hiragana: "がくせいはあしたがっこうへいく。",
    romaji: "gakusei wa ashita gakkou e iku.",
    chinese: "學生明天去學校。",
  ),
  "週": ExampleSentence(
    japanese: "学生は週に学校へ行く。",
    hiragana: "がくせいはしゅうにがっこうへいく。",
    romaji: "gakusei wa shuu ni gakkou e iku.",
    chinese: "學生每週去學校。",
  ),
  "月": ExampleSentence(
    japanese: "月は空にある。",
    hiragana: "つきはそらにある。",
    romaji: "tsuki wa sora ni aru.",
    chinese: "月亮在天空。",
  ),
  "年": ExampleSentence(
    japanese: "年は時間です。",
    hiragana: "としはじかんです。",
    romaji: "toshi wa jikan desu.",
    chinese: "年是時間。",
  ),
  "誕生日": ExampleSentence(
    japanese: "今日は誕生日です。",
    hiragana: "きょうはたんじょうびです。",
    romaji: "kyou wa tanjoubi desu.",
    chinese: "今天是生日。",
  ),
  "休み": ExampleSentence(
    japanese: "今日は休みです。",
    hiragana: "きょうはやすみです。",
    romaji: "kyou wa yasumi desu.",
    chinese: "今天休假。",
  ),
  "試験": ExampleSentence(
    japanese: "試験は難しい。",
    hiragana: "しけんはむずかしい。",
    romaji: "shiken wa muzukashii.",
    chinese: "考試很困難。",
  ),
  "宿題": ExampleSentence(
    japanese: "学生は宿題を書く。",
    hiragana: "がくせいはしゅくだいをかく。",
    romaji: "gakusei wa shukudai o kaku.",
    chinese: "學生寫作業。",
  ),
  "質問": ExampleSentence(
    japanese: "学生は質問に答える。",
    hiragana: "がくせいはしつもんにこたえる。",
    romaji: "gakusei wa shitsumon ni kotaeru.",
    chinese: "學生回答問題。",
  ),
  "答え": ExampleSentence(
    japanese: "学生は答えを書く。",
    hiragana: "がくせいはこたえをかく。",
    romaji: "gakusei wa kotae o kaku.",
    chinese: "學生寫答案。",
  ),
  "漢字": ExampleSentence(
    japanese: "学生は漢字を書く。",
    hiragana: "がくせいはかんじをかく。",
    romaji: "gakusei wa kanji o kaku.",
    chinese: "學生寫漢字。",
  ),
  "言葉": ExampleSentence(
    japanese: "学生は言葉を覚える。",
    hiragana: "がくせいはことばをおぼえる。",
    romaji: "gakusei wa kotoba o oboeru.",
    chinese: "學生記住單字。",
  ),
  "文章": ExampleSentence(
    japanese: "学生は文章を読む。",
    hiragana: "がくせいはぶんしょうをよむ。",
    romaji: "gakusei wa bunshou o yomu.",
    chinese: "學生讀文章。",
  ),
  "名前": ExampleSentence(
    japanese: "学生は名前を書く。",
    hiragana: "がくせいはなまえをかく。",
    romaji: "gakusei wa namae o kaku.",
    chinese: "學生寫名字。",
  ),
  "住所": ExampleSentence(
    japanese: "学生は住所を書く。",
    hiragana: "がくせいはじゅうしょをかく。",
    romaji: "gakusei wa juusho o kaku.",
    chinese: "學生寫地址。",
  ),
  "住所録": ExampleSentence(
    japanese: "学生は住所録を見る。",
    hiragana: "がくせいはじゅうしょろくをみる。",
    romaji: "gakusei wa juushoroku o miru.",
    chinese: "學生看通訊錄。",
  ),
  "国": ExampleSentence(
    japanese: "学生は国へ行く。",
    hiragana: "がくせいはくにへいく。",
    romaji: "gakusei wa kuni e iku.",
    chinese: "學生去國家。",
  ),
  "音楽": ExampleSentence(
    japanese: "学生は音楽を聞く。",
    hiragana: "がくせいはおんがくをきく。",
    romaji: "gakusei wa ongaku o kiku.",
    chinese: "學生聽音樂。",
  ),
  "歌": ExampleSentence(
    japanese: "子供は歌を歌う。",
    hiragana: "こどもはうたをうたう。",
    romaji: "kodomo wa uta o utau.",
    chinese: "小孩唱歌。",
  ),
  "映画": ExampleSentence(
    japanese: "学生は映画を見る。",
    hiragana: "がくせいはえいがをみる。",
    romaji: "gakusei wa eiga o miru.",
    chinese: "學生看電影。",
  ),
  "写真": ExampleSentence(
    japanese: "学生は写真を撮る。",
    hiragana: "がくせいはしゃしんをとる。",
    romaji: "gakusei wa shashin o toru.",
    chinese: "學生拍照。",
  ),
  "絵": ExampleSentence(
    japanese: "子供は絵を見る。",
    hiragana: "こどもはえをみる。",
    romaji: "kodomo wa e o miru.",
    chinese: "小孩看圖畫。",
  ),
  "色": ExampleSentence(
    japanese: "花の色は赤い。",
    hiragana: "はなのいろはあかい。",
    romaji: "hana no iro wa akai.",
    chinese: "花的顏色是紅色的。",
  ),
  "赤": ExampleSentence(
    japanese: "花は赤です。",
    hiragana: "はなはあかです。",
    romaji: "hana wa aka desu.",
    chinese: "花是紅色。",
  ),
  "青": ExampleSentence(
    japanese: "空は青です。",
    hiragana: "そらはあおです。",
    romaji: "sora wa ao desu.",
    chinese: "天空是藍色。",
  ),
  "白": ExampleSentence(
    japanese: "雪は白です。",
    hiragana: "ゆきはしろです。",
    romaji: "yuki wa shiro desu.",
    chinese: "雪是白色。",
  ),
  "黒": ExampleSentence(
    japanese: "猫は黒です。",
    hiragana: "ねこはくろです。",
    romaji: "neko wa kuro desu.",
    chinese: "貓是黑色。",
  ),
  "緑": ExampleSentence(
    japanese: "木は緑です。",
    hiragana: "きはみどりです。",
    romaji: "ki wa midori desu.",
    chinese: "樹木是綠色。",
  ),
  "茶色": ExampleSentence(
    japanese: "鞄は茶色です。",
    hiragana: "かばんはちゃいろです。",
    romaji: "kaban wa chairo desu.",
    chinese: "包包是咖啡色。",
  ),
  "体": ExampleSentence(
    japanese: "子供は体が丈夫です。",
    hiragana: "こどもはからだがじょうぶです。",
    romaji: "kodomo wa karada ga joubu desu.",
    chinese: "小孩的身體很健康。",
  ),
  "頭": ExampleSentence(
    japanese: "子供は頭が大きい。",
    hiragana: "こどもはあたまがおおきい。",
    romaji: "kodomo wa atama ga ookii.",
    chinese: "小孩的頭很大。",
  ),
  "目": ExampleSentence(
    japanese: "学生は目で見る。",
    hiragana: "がくせいはめでみる。",
    romaji: "gakusei wa me de miru.",
    chinese: "學生用眼睛看。",
  ),
  "耳": ExampleSentence(
    japanese: "学生は耳で聞く。",
    hiragana: "がくせいはみみできく。",
    romaji: "gakusei wa mimi de kiku.",
    chinese: "學生用耳朵聽。",
  ),
  "口": ExampleSentence(
    japanese: "子供は口を開ける。",
    hiragana: "こどもはくちをあける。",
    romaji: "kodomo wa kuchi o akeru.",
    chinese: "小孩張開嘴巴。",
  ),
  "鼻": ExampleSentence(
    japanese: "子供は鼻を見る。",
    hiragana: "こどもははなをみる。",
    romaji: "kodomo wa hana o miru.",
    chinese: "小孩看鼻子。",
  ),
  "手": ExampleSentence(
    japanese: "子供は手で本を取る。",
    hiragana: "こどもはてでほんをとる。",
    romaji: "kodomo wa te de hon o toru.",
    chinese: "小孩用手拿書。",
  ),
  "足": ExampleSentence(
    japanese: "学生は足で歩く。",
    hiragana: "がくせいはあしであるく。",
    romaji: "gakusei wa ashi de aruku.",
    chinese: "學生用腳走路。",
  ),
  "顔": ExampleSentence(
    japanese: "学生は顔を見る。",
    hiragana: "がくせいはかおをみる。",
    romaji: "gakusei wa kao o miru.",
    chinese: "學生看臉。",
  ),
  "心": ExampleSentence(
    japanese: "子供は心が大きい。",
    hiragana: "こどもはこころがおおきい。",
    romaji: "kodomo wa kokoro ga ookii.",
    chinese: "小孩的心很大。",
  ),
  "病気": ExampleSentence(
    japanese: "父は病気です。",
    hiragana: "ちちはびょうきです。",
    romaji: "chichi wa byouki desu.",
    chinese: "父親生病。",
  ),
  "薬": ExampleSentence(
    japanese: "父は薬を飲む。",
    hiragana: "ちちはくすりをのむ。",
    romaji: "chichi wa kusuri o nomu.",
    chinese: "父親喝藥。",
  ),
  "運動": ExampleSentence(
    japanese: "先生は学生に運動を教える。",
    hiragana: "せんせいはがくせいにうんどうをおしえる。",
    romaji: "sensei wa gakusei ni undou o oshieru.",
    chinese: "老師教學生運動。",
  ),
  "旅行": ExampleSentence(
    japanese: "学生は旅行が楽しい。",
    hiragana: "がくせいはりょこうがたのしい。",
    romaji: "gakusei wa ryokou ga tanoshii.",
    chinese: "學生覺得旅行很快樂。",
  ),
  "地図": ExampleSentence(
    japanese: "学生は地図を見る。",
    hiragana: "がくせいはちずをみる。",
    romaji: "gakusei wa chizu o miru.",
    chinese: "學生看地圖。",
  ),
  "道具": ExampleSentence(
    japanese: "学生は道具を使う。",
    hiragana: "がくせいはどうぐをつかう。",
    romaji: "gakusei wa dougu o tsukau.",
    chinese: "學生使用工具。",
  ),
  "荷物": ExampleSentence(
    japanese: "学生は荷物を取る。",
    hiragana: "がくせいはにもつをとる。",
    romaji: "gakusei wa nimotsu o toru.",
    chinese: "學生拿行李。",
  ),
  "仕事": ExampleSentence(
    japanese: "仕事が終わる。",
    hiragana: "しごとがおわる。",
    romaji: "shigoto ga owaru.",
    chinese: "工作結束。",
  ),
};
