class ExampleSentence {
  const ExampleSentence({
    required this.japanese,
    required this.hiragana,
    required this.romaji,
    required this.chinese,
  });

  final String japanese;
  final String hiragana;
  final String romaji;
  final String chinese;
}

ExampleSentence exampleSentenceFor(String kanji) {
  return _sentences[kanji]!;
}

const Map<String, ExampleSentence> _sentences = {
  "会う": ExampleSentence(
    japanese: "学生は先生に会う。",
    hiragana: "がくせいはせんせいにあう。",
    romaji: "gakusei wa sensei ni au.",
    chinese: "學生和老師見面。",
  ),
  "開ける": ExampleSentence(
    japanese: "学生はドアを開ける。",
    hiragana: "がくせいはドアをあける。",
    romaji: "gakusei wa doa o akeru.",
    chinese: "學生打開門。",
  ),
  "遊ぶ": ExampleSentence(
    japanese: "子供は公園で遊ぶ。",
    hiragana: "こどもはこうえんであそぶ。",
    romaji: "kodomo wa kouen de asobu.",
    chinese: "小孩在公園玩。",
  ),
  "浴びる": ExampleSentence(
    japanese: "子供は水を浴びる。",
    hiragana: "こどもはみずをあびる。",
    romaji: "kodomo wa mizu o abiru.",
    chinese: "小孩淋水。",
  ),
  "ある": ExampleSentence(
    japanese: "部屋に本がある。",
    hiragana: "へやにほんがある。",
    romaji: "heya ni hon ga aru.",
    chinese: "房間裡有書。",
  ),
  "歩く": ExampleSentence(
    japanese: "学生は道を歩く。",
    hiragana: "がくせいはみちをあるく。",
    romaji: "gakusei wa michi o aruku.",
    chinese: "學生走路。",
  ),
  "言う": ExampleSentence(
    japanese: "先生は言葉を言う。",
    hiragana: "せんせいはことばをいう。",
    romaji: "sensei wa kotoba o iu.",
    chinese: "老師說單字。",
  ),
  "行く": ExampleSentence(
    japanese: "学生は学校へ行く。",
    hiragana: "がくせいはがっこうへいく。",
    romaji: "gakusei wa gakkou e iku.",
    chinese: "學生去學校。",
  ),
  "急ぐ": ExampleSentence(
    japanese: "学生は駅へ急ぐ。",
    hiragana: "がくせいはえきへいそぐ。",
    romaji: "gakusei wa eki e isogu.",
    chinese: "學生趕去車站。",
  ),
  "いる": ExampleSentence(
    japanese: "教室に学生がいる。",
    hiragana: "きょうしつにがくせいがいる。",
    romaji: "kyoushitsu ni gakusei ga iru.",
    chinese: "教室裡有學生。",
  ),
  "歌う": ExampleSentence(
    japanese: "子供は歌を歌う。",
    hiragana: "こどもはうたをうたう。",
    romaji: "kodomo wa uta o utau.",
    chinese: "小孩唱歌。",
  ),
  "生まれる": ExampleSentence(
    japanese: "子供は家で生まれる。",
    hiragana: "こどもはいえでうまれる。",
    romaji: "kodomo wa ie de umareru.",
    chinese: "小孩在家出生。",
  ),
  "売る": ExampleSentence(
    japanese: "店は果物を売る。",
    hiragana: "みせはくだものをうる。",
    romaji: "mise wa kudamono o uru.",
    chinese: "商店賣水果。",
  ),
  "起きる": ExampleSentence(
    japanese: "学生は朝に起きる。",
    hiragana: "がくせいはあさにおきる。",
    romaji: "gakusei wa asa ni okiru.",
    chinese: "學生早晨起床。",
  ),
  "置く": ExampleSentence(
    japanese: "学生は本を机に置く。",
    hiragana: "がくせいはほんをつくえにおく。",
    romaji: "gakusei wa hon o tsukue ni oku.",
    chinese: "學生把書放在桌子上。",
  ),
  "送る": ExampleSentence(
    japanese: "母は子供に荷物を送る。",
    hiragana: "はははこどもににもつをおくる。",
    romaji: "haha wa kodomo ni nimotsu o okuru.",
    chinese: "母親送行李給小孩。",
  ),
  "教える": ExampleSentence(
    japanese: "先生は学生に漢字を教える。",
    hiragana: "せんせいはがくせいにかんじをおしえる。",
    romaji: "sensei wa gakusei ni kanji o oshieru.",
    chinese: "老師教學生漢字。",
  ),
  "押す": ExampleSentence(
    japanese: "学生はドアを押す。",
    hiragana: "がくせいはドアをおす。",
    romaji: "gakusei wa doa o osu.",
    chinese: "學生按門。",
  ),
  "覚える": ExampleSentence(
    japanese: "学生は言葉を覚える。",
    hiragana: "がくせいはことばをおぼえる。",
    romaji: "gakusei wa kotoba o oboeru.",
    chinese: "學生記住單字。",
  ),
  "終わる": ExampleSentence(
    japanese: "仕事が終わる。",
    hiragana: "しごとがおわる。",
    romaji: "shigoto ga owaru.",
    chinese: "工作結束。",
  ),
  "買う": ExampleSentence(
    japanese: "学生は本を買う。",
    hiragana: "がくせいはほんをかう。",
    romaji: "gakusei wa hon o kau.",
    chinese: "學生買書。",
  ),
  "返す": ExampleSentence(
    japanese: "学生は本を返す。",
    hiragana: "がくせいはほんをかえす。",
    romaji: "gakusei wa hon o kaesu.",
    chinese: "學生歸還書。",
  ),
  "帰る": ExampleSentence(
    japanese: "学生は家へ帰る。",
    hiragana: "がくせいはいえへかえる。",
    romaji: "gakusei wa ie e kaeru.",
    chinese: "學生回家。",
  ),
  "書く": ExampleSentence(
    japanese: "学生は漢字を書く。",
    hiragana: "がくせいはかんじをかく。",
    romaji: "gakusei wa kanji o kaku.",
    chinese: "學生寫漢字。",
  ),
  "貸す": ExampleSentence(
    japanese: "友達は学生に本を貸す。",
    hiragana: "ともだちはがくせいにほんをかす。",
    romaji: "tomodachi wa gakusei ni hon o kasu.",
    chinese: "朋友把書借給學生。",
  ),
  "借りる": ExampleSentence(
    japanese: "学生は友達に本を借りる。",
    hiragana: "がくせいはともだちにほんをかりる。",
    romaji: "gakusei wa tomodachi ni hon o kariru.",
    chinese: "學生向朋友借書。",
  ),
  "消える": ExampleSentence(
    japanese: "雪が消える。",
    hiragana: "ゆきがきえる。",
    romaji: "yuki ga kieru.",
    chinese: "雪消失。",
  ),
  "聞く": ExampleSentence(
    japanese: "学生は音楽を聞く。",
    hiragana: "がくせいはおんがくをきく。",
    romaji: "gakusei wa ongaku o kiku.",
    chinese: "學生聽音樂。",
  ),
  "切る": ExampleSentence(
    japanese: "母は野菜を切る。",
    hiragana: "はははやさいをきる。",
    romaji: "haha wa yasai o kiru.",
    chinese: "母親切蔬菜。",
  ),
  "着る": ExampleSentence(
    japanese: "子供は服を着る。",
    hiragana: "こどもはふくをきる。",
    romaji: "kodomo wa fuku o kiru.",
    chinese: "小孩穿衣服。",
  ),
  "来る": ExampleSentence(
    japanese: "友達は家へ来る。",
    hiragana: "ともだちはいえへくる。",
    romaji: "tomodachi wa ie e kuru.",
    chinese: "朋友來家。",
  ),
  "消す": ExampleSentence(
    japanese: "子供は絵を消す。",
    hiragana: "こどもはえをけす。",
    romaji: "kodomo wa e o kesu.",
    chinese: "小孩把圖畫擦掉。",
  ),
  "答える": ExampleSentence(
    japanese: "学生は質問に答える。",
    hiragana: "がくせいはしつもんにこたえる。",
    romaji: "gakusei wa shitsumon ni kotaeru.",
    chinese: "學生回答問題。",
  ),
  "困る": ExampleSentence(
    japanese: "学生は宿題に困る。",
    hiragana: "がくせいはしゅくだいにこまる。",
    romaji: "gakusei wa shukudai ni komaru.",
    chinese: "學生為作業所困擾。",
  ),
  "座る": ExampleSentence(
    japanese: "学生は椅子に座る。",
    hiragana: "がくせいはいすにすわる。",
    romaji: "gakusei wa isu ni suwaru.",
    chinese: "學生坐在椅子上。",
  ),
  "住む": ExampleSentence(
    japanese: "学生は家に住む。",
    hiragana: "がくせいはいえにすむ。",
    romaji: "gakusei wa ie ni sumu.",
    chinese: "學生住在家裡。",
  ),
  "出す": ExampleSentence(
    japanese: "学生は宿題を出す。",
    hiragana: "がくせいはしゅくだいをだす。",
    romaji: "gakusei wa shukudai o dasu.",
    chinese: "學生交出作業。",
  ),
  "立つ": ExampleSentence(
    japanese: "子供は道に立つ。",
    hiragana: "こどもはみちにたつ。",
    romaji: "kodomo wa michi ni tatsu.",
    chinese: "小孩站在路上。",
  ),
  "頼む": ExampleSentence(
    japanese: "子供は母に仕事を頼む。",
    hiragana: "こどもはははにしごとをたのむ。",
    romaji: "kodomo wa haha ni shigoto o tanomu.",
    chinese: "小孩拜託母親做事。",
  ),
  "食べる": ExampleSentence(
    japanese: "学生はご飯を食べる。",
    hiragana: "がくせいはごはんをたべる。",
    romaji: "gakusei wa gohan o taberu.",
    chinese: "學生吃飯。",
  ),
  "使う": ExampleSentence(
    japanese: "学生は辞書を使う。",
    hiragana: "がくせいはじしょをつかう。",
    romaji: "gakusei wa jisho o tsukau.",
    chinese: "學生使用字典。",
  ),
  "作る": ExampleSentence(
    japanese: "母はご飯を作る。",
    hiragana: "はははごはんをつくる。",
    romaji: "haha wa gohan o tsukuru.",
    chinese: "母親做飯。",
  ),
  "手伝う": ExampleSentence(
    japanese: "子供は母を手伝う。",
    hiragana: "こどもはははをてつだう。",
    romaji: "kodomo wa haha o tetsudau.",
    chinese: "小孩幫忙母親。",
  ),
  "出る": ExampleSentence(
    japanese: "学生は家を出る。",
    hiragana: "がくせいはいえをでる。",
    romaji: "gakusei wa ie o deru.",
    chinese: "學生離開家。",
  ),
  "撮る": ExampleSentence(
    japanese: "学生は写真を撮る。",
    hiragana: "がくせいはしゃしんをとる。",
    romaji: "gakusei wa shashin o toru.",
    chinese: "學生拍照。",
  ),
  "取る": ExampleSentence(
    japanese: "学生は荷物を取る。",
    hiragana: "がくせいはにもつをとる。",
    romaji: "gakusei wa nimotsu o toru.",
    chinese: "學生拿行李。",
  ),
  "飲む": ExampleSentence(
    japanese: "学生は水を飲む。",
    hiragana: "がくせいはみずをのむ。",
    romaji: "gakusei wa mizu o nomu.",
    chinese: "學生喝水。",
  ),
  "入る": ExampleSentence(
    japanese: "学生は部屋に入る。",
    hiragana: "がくせいはへやにはいる。",
    romaji: "gakusei wa heya ni hairu.",
    chinese: "學生進入房間。",
  ),
  "話す": ExampleSentence(
    japanese: "学生は友達と話す。",
    hiragana: "がくせいはともだちとはなす。",
    romaji: "gakusei wa tomodachi to hanasu.",
    chinese: "學生和朋友說話。",
  ),
  "待つ": ExampleSentence(
    japanese: "学生は駅で待つ。",
    hiragana: "がくせいはえきでまつ。",
    romaji: "gakusei wa eki de matsu.",
    chinese: "學生在車站等待。",
  ),
  "見る": ExampleSentence(
    japanese: "学生は映画を見る。",
    hiragana: "がくせいはえいがをみる。",
    romaji: "gakusei wa eiga o miru.",
    chinese: "學生看電影。",
  ),
  "読む": ExampleSentence(
    japanese: "学生は本を読む。",
    hiragana: "がくせいはほんをよむ。",
    romaji: "gakusei wa hon o yomu.",
    chinese: "學生讀書。",
  ),
  "大きい": ExampleSentence(
    japanese: "学校は大きい。",
    hiragana: "がっこうはおおきい。",
    romaji: "gakkou wa ookii.",
    chinese: "學校很大。",
  ),
  "小さい": ExampleSentence(
    japanese: "猫は小さい。",
    hiragana: "ねこはちいさい。",
    romaji: "neko wa chiisai.",
    chinese: "貓很小。",
  ),
  "高い": ExampleSentence(
    japanese: "山は高い。",
    hiragana: "やまはたかい。",
    romaji: "yama wa takai.",
    chinese: "山很高。",
  ),
  "安い": ExampleSentence(
    japanese: "本は安い。",
    hiragana: "ほんはやすい。",
    romaji: "hon wa yasui.",
    chinese: "書很便宜。",
  ),
  "新しい": ExampleSentence(
    japanese: "車は新しい。",
    hiragana: "くるまはあたらしい。",
    romaji: "kuruma wa atarashii.",
    chinese: "汽車是新的。",
  ),
  "古い": ExampleSentence(
    japanese: "家は古い。",
    hiragana: "いえはふるい。",
    romaji: "ie wa furui.",
    chinese: "家是舊的。",
  ),
  "良い": ExampleSentence(
    japanese: "天気は良い。",
    hiragana: "てんきはよい。",
    romaji: "tenki wa yoi.",
    chinese: "天氣很好。",
  ),
  "悪い": ExampleSentence(
    japanese: "天気は悪い。",
    hiragana: "てんきはわるい。",
    romaji: "tenki wa warui.",
    chinese: "天氣很壞。",
  ),
  "長い": ExampleSentence(
    japanese: "道は長い。",
    hiragana: "みちはながい。",
    romaji: "michi wa nagai.",
    chinese: "道路很長。",
  ),
  "短い": ExampleSentence(
    japanese: "名前は短い。",
    hiragana: "なまえはみじかい。",
    romaji: "namae wa mijikai.",
    chinese: "名字很短。",
  ),
  "多い": ExampleSentence(
    japanese: "人は多い。",
    hiragana: "ひとはおおい。",
    romaji: "hito wa ooi.",
    chinese: "人很多。",
  ),
  "少ない": ExampleSentence(
    japanese: "人は少ない。",
    hiragana: "ひとはすくない。",
    romaji: "hito wa sukunai.",
    chinese: "人很少。",
  ),
  "暑い": ExampleSentence(
    japanese: "夏は暑い。",
    hiragana: "なつはあつい。",
    romaji: "natsu wa atsui.",
    chinese: "夏天很炎熱。",
  ),
  "寒い": ExampleSentence(
    japanese: "冬は寒い。",
    hiragana: "ふゆはさむい。",
    romaji: "fuyu wa samui.",
    chinese: "冬天很寒冷。",
  ),
  "熱い": ExampleSentence(
    japanese: "お茶は熱い。",
    hiragana: "おちゃはあつい。",
    romaji: "ocha wa atsui.",
    chinese: "茶很熱。",
  ),
  "冷たい": ExampleSentence(
    japanese: "水は冷たい。",
    hiragana: "みずはつめたい。",
    romaji: "mizu wa tsumetai.",
    chinese: "水很冰冷。",
  ),
  "忙しい": ExampleSentence(
    japanese: "先生は忙しい。",
    hiragana: "せんせいはいそがしい。",
    romaji: "sensei wa isogashii.",
    chinese: "老師很忙碌。",
  ),
  "暇": ExampleSentence(
    japanese: "学生は暇です。",
    hiragana: "がくせいはひまです。",
    romaji: "gakusei wa hima desu.",
    chinese: "學生有空。",
  ),
  "難しい": ExampleSentence(
    japanese: "試験は難しい。",
    hiragana: "しけんはむずかしい。",
    romaji: "shiken wa muzukashii.",
    chinese: "考試很困難。",
  ),
  "易しい": ExampleSentence(
    japanese: "宿題は易しい。",
    hiragana: "しゅくだいはやさしい。",
    romaji: "shukudai wa yasashii.",
    chinese: "作業很容易。",
  ),
  "楽しい": ExampleSentence(
    japanese: "旅行は楽しい。",
    hiragana: "りょこうはたのしい。",
    romaji: "ryokou wa tanoshii.",
    chinese: "旅行很快樂。",
  ),
  "面白い": ExampleSentence(
    japanese: "映画は面白い。",
    hiragana: "えいがはおもしろい。",
    romaji: "eiga wa omoshiroi.",
    chinese: "電影很有趣。",
  ),
  "つまらない": ExampleSentence(
    japanese: "映画はつまらない。",
    hiragana: "えいがはつまらない。",
    romaji: "eiga wa tsumaranai.",
    chinese: "電影很無聊。",
  ),
  "明るい": ExampleSentence(
    japanese: "部屋は明るい。",
    hiragana: "へやはあかるい。",
    romaji: "heya wa akarui.",
    chinese: "房間很明亮。",
  ),
  "暗い": ExampleSentence(
    japanese: "夜は暗い。",
    hiragana: "よるはくらい。",
    romaji: "yoru wa kurai.",
    chinese: "晚上很昏暗。",
  ),
  "近い": ExampleSentence(
    japanese: "駅は近い。",
    hiragana: "えきはちかい。",
    romaji: "eki wa chikai.",
    chinese: "車站很近。",
  ),
  "遠い": ExampleSentence(
    japanese: "国は遠い。",
    hiragana: "くにはとおい。",
    romaji: "kuni wa tooi.",
    chinese: "國家很遠。",
  ),
  "早い": ExampleSentence(
    japanese: "朝は早い。",
    hiragana: "あさははやい。",
    romaji: "asa wa hayai.",
    chinese: "早晨很早。",
  ),
  "速い": ExampleSentence(
    japanese: "電車は速い。",
    hiragana: "でんしゃははやい。",
    romaji: "densha wa hayai.",
    chinese: "電車很快。",
  ),
  "遅い": ExampleSentence(
    japanese: "電車は遅い。",
    hiragana: "でんしゃはおそい。",
    romaji: "densha wa osoi.",
    chinese: "電車很慢。",
  ),
  "重い": ExampleSentence(
    japanese: "荷物は重い。",
    hiragana: "にもつはおもい。",
    romaji: "nimotsu wa omoi.",
    chinese: "行李很重。",
  ),
  "軽い": ExampleSentence(
    japanese: "鞄は軽い。",
    hiragana: "かばんはかるい。",
    romaji: "kaban wa karui.",
    chinese: "包包很輕。",
  ),
  "甘い": ExampleSentence(
    japanese: "果物は甘い。",
    hiragana: "くだものはあまい。",
    romaji: "kudamono wa amai.",
    chinese: "水果很甜。",
  ),
  "辛い": ExampleSentence(
    japanese: "肉は辛い。",
    hiragana: "にくはからい。",
    romaji: "niku wa karai.",
    chinese: "肉很辣。",
  ),
  "塩辛い": ExampleSentence(
    japanese: "魚は塩辛い。",
    hiragana: "さかなはしおからい。",
    romaji: "sakana wa shiokarai.",
    chinese: "魚很鹹。",
  ),
  "酸っぱい": ExampleSentence(
    japanese: "果物は酸っぱい。",
    hiragana: "くだものはすっぱい。",
    romaji: "kudamono wa suppai.",
    chinese: "水果很酸。",
  ),
  "美味しい": ExampleSentence(
    japanese: "ご飯は美味しい。",
    hiragana: "ごはんはおいしい。",
    romaji: "gohan wa oishii.",
    chinese: "飯很好吃。",
  ),
  "まずい": ExampleSentence(
    japanese: "食べ物はまずい。",
    hiragana: "たべものはまずい。",
    romaji: "tabemono wa mazui.",
    chinese: "食物很難吃。",
  ),
  "白い": ExampleSentence(
    japanese: "雪は白い。",
    hiragana: "ゆきはしろい。",
    romaji: "yuki wa shiroi.",
    chinese: "雪是白色的。",
  ),
  "黒い": ExampleSentence(
    japanese: "猫は黒い。",
    hiragana: "ねこはくろい。",
    romaji: "neko wa kuroi.",
    chinese: "貓是黑色的。",
  ),
  "赤い": ExampleSentence(
    japanese: "花は赤い。",
    hiragana: "はなはあかい。",
    romaji: "hana wa akai.",
    chinese: "花是紅色的。",
  ),
  "青い": ExampleSentence(
    japanese: "空は青い。",
    hiragana: "そらはあおい。",
    romaji: "sora wa aoi.",
    chinese: "天空是藍色的。",
  ),
  "若い": ExampleSentence(
    japanese: "学生は若い。",
    hiragana: "がくせいはわかい。",
    romaji: "gakusei wa wakai.",
    chinese: "學生很年輕。",
  ),
  "有名": ExampleSentence(
    japanese: "大学は有名です。",
    hiragana: "だいがくはゆうめいです。",
    romaji: "daigaku wa yuumei desu.",
    chinese: "大學很有名。",
  ),
  "元気": ExampleSentence(
    japanese: "子供は元気です。",
    hiragana: "こどもはげんきです。",
    romaji: "kodomo wa genki desu.",
    chinese: "小孩很有精神。",
  ),
  "親切": ExampleSentence(
    japanese: "先生は親切です。",
    hiragana: "せんせいはしんせつです。",
    romaji: "sensei wa shinsetsu desu.",
    chinese: "老師很親切。",
  ),
  "静か": ExampleSentence(
    japanese: "図書館は静かです。",
    hiragana: "としょかんはしずかです。",
    romaji: "toshokan wa shizuka desu.",
    chinese: "圖書館很安靜。",
  ),
  "賑やか": ExampleSentence(
    japanese: "市場は賑やかです。",
    hiragana: "いちばはにぎやかです。",
    romaji: "ichiba wa nigiyaka desu.",
    chinese: "市場很熱鬧。",
  ),
  "便利": ExampleSentence(
    japanese: "電車は便利です。",
    hiragana: "でんしゃはべんりです。",
    romaji: "densha wa benri desu.",
    chinese: "電車很方便。",
  ),
  "丈夫": ExampleSentence(
    japanese: "体は丈夫です。",
    hiragana: "からだはじょうぶです。",
    romaji: "karada wa joubu desu.",
    chinese: "身體很健康。",
  ),
  "先生": ExampleSentence(
    japanese: "先生は学校で教える。",
    hiragana: "せんせいはがっこうでおしえる。",
    romaji: "sensei wa gakkou de oshieru.",
    chinese: "老師在學校教。",
  ),
  "学生": ExampleSentence(
    japanese: "学生は本を読む。",
    hiragana: "がくせいはほんをよむ。",
    romaji: "gakusei wa hon o yomu.",
    chinese: "學生讀書。",
  ),
  "友達": ExampleSentence(
    japanese: "友達は家へ来る。",
    hiragana: "ともだちはいえへくる。",
    romaji: "tomodachi wa ie e kuru.",
    chinese: "朋友來家。",
  ),
  "子供": ExampleSentence(
    japanese: "子供は公園で遊ぶ。",
    hiragana: "こどもはこうえんであそぶ。",
    romaji: "kodomo wa kouen de asobu.",
    chinese: "小孩在公園玩。",
  ),
  "人": ExampleSentence(
    japanese: "人は部屋にいる。",
    hiragana: "ひとはへやにいる。",
    romaji: "hito wa heya ni iru.",
    chinese: "人在房間裡。",
  ),
  "男": ExampleSentence(
    japanese: "男は道を歩く。",
    hiragana: "おとこはみちをあるく。",
    romaji: "otoko wa michi o aruku.",
    chinese: "男人走路。",
  ),
  "女": ExampleSentence(
    japanese: "女は花を見る。",
    hiragana: "おんなははなをみる。",
    romaji: "onna wa hana o miru.",
    chinese: "女人看花。",
  ),
  "男の子": ExampleSentence(
    japanese: "男の子は公園で遊ぶ。",
    hiragana: "おとこのこはこうえんであそぶ。",
    romaji: "otokonoko wa kouen de asobu.",
    chinese: "男孩在公園玩。",
  ),
  "女の子": ExampleSentence(
    japanese: "女の子は歌を歌う。",
    hiragana: "おんなのこはうたをうたう。",
    romaji: "onnanoko wa uta o utau.",
    chinese: "女孩唱歌。",
  ),
  "父": ExampleSentence(
    japanese: "父は会社へ行く。",
    hiragana: "ちちはかいしゃへいく。",
    romaji: "chichi wa kaisha e iku.",
    chinese: "父親去公司。",
  ),
  "母": ExampleSentence(
    japanese: "母はご飯を作る。",
    hiragana: "はははごはんをつくる。",
    romaji: "haha wa gohan o tsukuru.",
    chinese: "母親做飯。",
  ),
  "兄": ExampleSentence(
    japanese: "兄は学生に本を貸す。",
    hiragana: "あにはがくせいにほんをかす。",
    romaji: "ani wa gakusei ni hon o kasu.",
    chinese: "哥哥把書借給學生。",
  ),
  "姉": ExampleSentence(
    japanese: "姉は歌を歌う。",
    hiragana: "あねはうたをうたう。",
    romaji: "ane wa uta o utau.",
    chinese: "姐姐唱歌。",
  ),
  "弟": ExampleSentence(
    japanese: "弟は水を飲む。",
    hiragana: "おとうとはみずをのむ。",
    romaji: "otouto wa mizu o nomu.",
    chinese: "弟弟喝水。",
  ),
  "妹": ExampleSentence(
    japanese: "妹は絵を見る。",
    hiragana: "いもうとはえをみる。",
    romaji: "imouto wa e o miru.",
    chinese: "妹妹看圖畫。",
  ),
  "医者": ExampleSentence(
    japanese: "医者は病院にいる。",
    hiragana: "いしゃはびょういんにいる。",
    romaji: "isha wa byouin ni iru.",
    chinese: "醫生在醫院。",
  ),
  "看護師": ExampleSentence(
    japanese: "看護師は病院にいる。",
    hiragana: "かんごしはびょういんにいる。",
    romaji: "kangoshi wa byouin ni iru.",
    chinese: "護士在醫院。",
  ),
  "学校": ExampleSentence(
    japanese: "学生は学校へ行く。",
    hiragana: "がくせいはがっこうへいく。",
    romaji: "gakusei wa gakkou e iku.",
    chinese: "學生去學校。",
  ),
  "家": ExampleSentence(
    japanese: "学生は家へ帰る。",
    hiragana: "がくせいはいえへかえる。",
    romaji: "gakusei wa ie e kaeru.",
    chinese: "學生回家。",
  ),
  "部屋": ExampleSentence(
    japanese: "学生は部屋に入る。",
    hiragana: "がくせいはへやにはいる。",
    romaji: "gakusei wa heya ni hairu.",
    chinese: "學生進入房間。",
  ),
  "駅": ExampleSentence(
    japanese: "学生は駅へ行く。",
    hiragana: "がくせいはえきへいく。",
    romaji: "gakusei wa eki e iku.",
    chinese: "學生去車站。",
  ),
  "銀行": ExampleSentence(
    japanese: "学生は銀行へ行く。",
    hiragana: "がくせいはぎんこうへいく。",
    romaji: "gakusei wa ginkou e iku.",
    chinese: "學生去銀行。",
  ),
  "病院": ExampleSentence(
    japanese: "学生は病院へ行く。",
    hiragana: "がくせいはびょういんへいく。",
    romaji: "gakusei wa byouin e iku.",
    chinese: "學生去醫院。",
  ),
  "会社": ExampleSentence(
    japanese: "父は会社へ行く。",
    hiragana: "ちちはかいしゃへいく。",
    romaji: "chichi wa kaisha e iku.",
    chinese: "父親去公司。",
  ),
  "店": ExampleSentence(
    japanese: "母は店へ行く。",
    hiragana: "はははみせへいく。",
    romaji: "haha wa mise e iku.",
    chinese: "母親去商店。",
  ),
  "郵便局": ExampleSentence(
    japanese: "学生は郵便局へ行く。",
    hiragana: "がくせいはゆうびんきょくへいく。",
    romaji: "gakusei wa yuubinkyoku e iku.",
    chinese: "學生去郵局。",
  ),
  "図書館": ExampleSentence(
    japanese: "学生は図書館へ行く。",
    hiragana: "がくせいはとしょかんへいく。",
    romaji: "gakusei wa toshokan e iku.",
    chinese: "學生去圖書館。",
  ),
  "公園": ExampleSentence(
    japanese: "子供は公園で遊ぶ。",
    hiragana: "こどもはこうえんであそぶ。",
    romaji: "kodomo wa kouen de asobu.",
    chinese: "小孩在公園玩。",
  ),
  "大学": ExampleSentence(
    japanese: "学生は大学へ行く。",
    hiragana: "がくせいはだいがくへいく。",
    romaji: "gakusei wa daigaku e iku.",
    chinese: "學生去大學。",
  ),
  "教室": ExampleSentence(
    japanese: "学生は教室に入る。",
    hiragana: "がくせいはきょうしつにはいる。",
    romaji: "gakusei wa kyoushitsu ni hairu.",
    chinese: "學生進入教室。",
  ),
  "空港": ExampleSentence(
    japanese: "学生は空港へ行く。",
    hiragana: "がくせいはくうこうへいく。",
    romaji: "gakusei wa kuukou e iku.",
    chinese: "學生去機場。",
  ),
  "海": ExampleSentence(
    japanese: "学生は海へ行く。",
    hiragana: "がくせいはうみへいく。",
    romaji: "gakusei wa umi e iku.",
    chinese: "學生去海洋。",
  ),
  "山": ExampleSentence(
    japanese: "学生は山へ行く。",
    hiragana: "がくせいはやまへいく。",
    romaji: "gakusei wa yama e iku.",
    chinese: "學生去山。",
  ),
  "川": ExampleSentence(
    japanese: "学生は川へ行く。",
    hiragana: "がくせいはかわへいく。",
    romaji: "gakusei wa kawa e iku.",
    chinese: "學生去河川。",
  ),
  "湖": ExampleSentence(
    japanese: "学生は湖へ行く。",
    hiragana: "がくせいはみずうみへいく。",
    romaji: "gakusei wa mizuumi e iku.",
    chinese: "學生去湖。",
  ),
  "森": ExampleSentence(
    japanese: "学生は森へ行く。",
    hiragana: "がくせいはもりへいく。",
    romaji: "gakusei wa mori e iku.",
    chinese: "學生去森林。",
  ),
  "ホテル": ExampleSentence(
    japanese: "学生はホテルへ行く。",
    hiragana: "がくせいはホテルへいく。",
    romaji: "gakusei wa hoteru e iku.",
    chinese: "學生去飯店。",
  ),
  "市場": ExampleSentence(
    japanese: "母は市場へ行く。",
    hiragana: "はははいちばへいく。",
    romaji: "haha wa ichiba e iku.",
    chinese: "母親去市場。",
  ),
  "川辺": ExampleSentence(
    japanese: "子供は川辺で遊ぶ。",
    hiragana: "こどもはかわべであそぶ。",
    romaji: "kodomo wa kawabe de asobu.",
    chinese: "小孩在河邊玩。",
  ),
  "場所": ExampleSentence(
    japanese: "公園は場所です。",
    hiragana: "こうえんはばしょです。",
    romaji: "kouen wa basho desu.",
    chinese: "公園是一個地方。",
  ),
  "本": ExampleSentence(
    japanese: "学生は本を読む。",
    hiragana: "がくせいはほんをよむ。",
    romaji: "gakusei wa hon o yomu.",
    chinese: "學生讀書。",
  ),
  "新聞": ExampleSentence(
    japanese: "学生は新聞を読む。",
    hiragana: "がくせいはしんぶんをよむ。",
    romaji: "gakusei wa shinbun o yomu.",
    chinese: "學生讀報紙。",
  ),
  "雑誌": ExampleSentence(
    japanese: "学生は雑誌を読む。",
    hiragana: "がくせいはざっしをよむ。",
    romaji: "gakusei wa zasshi o yomu.",
    chinese: "學生讀雜誌。",
  ),
  "辞書": ExampleSentence(
    japanese: "学生は辞書を使う。",
    hiragana: "がくせいはじしょをつかう。",
    romaji: "gakusei wa jisho o tsukau.",
    chinese: "學生使用字典。",
  ),
  "机": ExampleSentence(
    japanese: "学生は本を机に置く。",
    hiragana: "がくせいはほんをつくえにおく。",
    romaji: "gakusei wa hon o tsukue ni oku.",
    chinese: "學生把書放在桌子上。",
  ),
  "椅子": ExampleSentence(
    japanese: "学生は椅子に座る。",
    hiragana: "がくせいはいすにすわる。",
    romaji: "gakusei wa isu ni suwaru.",
    chinese: "學生坐在椅子上。",
  ),
  "時計": ExampleSentence(
    japanese: "学生は時計を見る。",
    hiragana: "がくせいはとけいをみる。",
    romaji: "gakusei wa tokei o miru.",
    chinese: "學生看時鐘。",
  ),
  "電話": ExampleSentence(
    japanese: "学生は電話を使う。",
    hiragana: "がくせいはでんわをつかう。",
    romaji: "gakusei wa denwa o tsukau.",
    chinese: "學生使用電話。",
  ),
  "携帯": ExampleSentence(
    japanese: "学生は携帯を使う。",
    hiragana: "がくせいはけいたいをつかう。",
    romaji: "gakusei wa keitai o tsukau.",
    chinese: "學生使用手機。",
  ),
  "車": ExampleSentence(
    japanese: "学生は車で行く。",
    hiragana: "がくせいはくるまでいく。",
    romaji: "gakusei wa kuruma de iku.",
    chinese: "學生坐汽車去。",
  ),
  "電車": ExampleSentence(
    japanese: "学生は電車で行く。",
    hiragana: "がくせいはでんしゃでいく。",
    romaji: "gakusei wa densha de iku.",
    chinese: "學生坐電車去。",
  ),
  "飛行機": ExampleSentence(
    japanese: "学生は飛行機で行く。",
    hiragana: "がくせいはひこうきでいく。",
    romaji: "gakusei wa hikouki de iku.",
    chinese: "學生坐飛機去。",
  ),
  "船": ExampleSentence(
    japanese: "学生は船で行く。",
    hiragana: "がくせいはふねでいく。",
    romaji: "gakusei wa fune de iku.",
    chinese: "學生坐船去。",
  ),
  "自転車": ExampleSentence(
    japanese: "学生は自転車で行く。",
    hiragana: "がくせいはじてんしゃでいく。",
    romaji: "gakusei wa jitensha de iku.",
    chinese: "學生騎腳踏車去。",
  ),
  "道": ExampleSentence(
    japanese: "学生は道を歩く。",
    hiragana: "がくせいはみちをあるく。",
    romaji: "gakusei wa michi o aruku.",
    chinese: "學生走路。",
  ),
  "窓": ExampleSentence(
    japanese: "学生は窓を開ける。",
    hiragana: "がくせいはまどをあける。",
    romaji: "gakusei wa mado o akeru.",
    chinese: "學生打開窗戶。",
  ),
  "ドア": ExampleSentence(
    japanese: "学生はドアを開ける。",
    hiragana: "がくせいはドアをあける。",
    romaji: "gakusei wa doa o akeru.",
    chinese: "學生打開門。",
  ),
  "鍵": ExampleSentence(
    japanese: "学生は鍵を使う。",
    hiragana: "がくせいはかぎをつかう。",
    romaji: "gakusei wa kagi o tsukau.",
    chinese: "學生使用鑰匙。",
  ),
  "傘": ExampleSentence(
    japanese: "学生は傘を使う。",
    hiragana: "がくせいはかさをつかう。",
    romaji: "gakusei wa kasa o tsukau.",
    chinese: "學生使用雨傘。",
  ),
  "靴": ExampleSentence(
    japanese: "学生は靴を買う。",
    hiragana: "がくせいはくつをかう。",
    romaji: "gakusei wa kutsu o kau.",
    chinese: "學生買鞋子。",
  ),
  "服": ExampleSentence(
    japanese: "子供は服を着る。",
    hiragana: "こどもはふくをきる。",
    romaji: "kodomo wa fuku o kiru.",
    chinese: "小孩穿衣服。",
  ),
  "帽子": ExampleSentence(
    japanese: "子供は帽子を買う。",
    hiragana: "こどもはぼうしをかう。",
    romaji: "kodomo wa boushi o kau.",
    chinese: "小孩買帽子。",
  ),
  "鞄": ExampleSentence(
    japanese: "学生は鞄を使う。",
    hiragana: "がくせいはかばんをつかう。",
    romaji: "gakusei wa kaban o tsukau.",
    chinese: "學生使用包包。",
  ),
  "財布": ExampleSentence(
    japanese: "学生は財布を使う。",
    hiragana: "がくせいはさいふをつかう。",
    romaji: "gakusei wa saifu o tsukau.",
    chinese: "學生使用錢包。",
  ),
  "お金": ExampleSentence(
    japanese: "学生はお金を使う。",
    hiragana: "がくせいはおかねをつかう。",
    romaji: "gakusei wa okane o tsukau.",
    chinese: "學生使用金錢。",
  ),
  "切符": ExampleSentence(
    japanese: "学生は切符を買う。",
    hiragana: "がくせいはきっぷをかう。",
    romaji: "gakusei wa kippu o kau.",
    chinese: "學生買車票。",
  ),
  "食べ物": ExampleSentence(
    japanese: "学生は食べ物を食べる。",
    hiragana: "がくせいはたべものをたべる。",
    romaji: "gakusei wa tabemono o taberu.",
    chinese: "學生吃食物。",
  ),
  "ご飯": ExampleSentence(
    japanese: "学生はご飯を食べる。",
    hiragana: "がくせいはごはんをたべる。",
    romaji: "gakusei wa gohan o taberu.",
    chinese: "學生吃飯。",
  ),
  "朝ご飯": ExampleSentence(
    japanese: "学生は朝ご飯を食べる。",
    hiragana: "がくせいはあさごはんをたべる。",
    romaji: "gakusei wa asagohan o taberu.",
    chinese: "學生吃早餐。",
  ),
  "昼ご飯": ExampleSentence(
    japanese: "学生は昼ご飯を食べる。",
    hiragana: "がくせいはひるごはんをたべる。",
    romaji: "gakusei wa hirugohan o taberu.",
    chinese: "學生吃午餐。",
  ),
  "晩ご飯": ExampleSentence(
    japanese: "学生は晩ご飯を食べる。",
    hiragana: "がくせいはばんごはんをたべる。",
    romaji: "gakusei wa bangohan o taberu.",
    chinese: "學生吃晚餐。",
  ),
  "果物": ExampleSentence(
    japanese: "学生は果物を食べる。",
    hiragana: "がくせいはくだものをたべる。",
    romaji: "gakusei wa kudamono o taberu.",
    chinese: "學生吃水果。",
  ),
  "野菜": ExampleSentence(
    japanese: "学生は野菜を食べる。",
    hiragana: "がくせいはやさいをたべる。",
    romaji: "gakusei wa yasai o taberu.",
    chinese: "學生吃蔬菜。",
  ),
  "肉": ExampleSentence(
    japanese: "学生は肉を食べる。",
    hiragana: "がくせいはにくをたべる。",
    romaji: "gakusei wa niku o taberu.",
    chinese: "學生吃肉。",
  ),
  "魚": ExampleSentence(
    japanese: "学生は魚を食べる。",
    hiragana: "がくせいはさかなをたべる。",
    romaji: "gakusei wa sakana o taberu.",
    chinese: "學生吃魚。",
  ),
  "卵": ExampleSentence(
    japanese: "学生は卵を食べる。",
    hiragana: "がくせいはたまごをたべる。",
    romaji: "gakusei wa tamago o taberu.",
    chinese: "學生吃雞蛋。",
  ),
  "飲み物": ExampleSentence(
    japanese: "学生は飲み物を飲む。",
    hiragana: "がくせいはのみものをのむ。",
    romaji: "gakusei wa nomimono o nomu.",
    chinese: "學生喝飲料。",
  ),
  "水": ExampleSentence(
    japanese: "学生は水を飲む。",
    hiragana: "がくせいはみずをのむ。",
    romaji: "gakusei wa mizu o nomu.",
    chinese: "學生喝水。",
  ),
  "お茶": ExampleSentence(
    japanese: "学生はお茶を飲む。",
    hiragana: "がくせいはおちゃをのむ。",
    romaji: "gakusei wa ocha o nomu.",
    chinese: "學生喝茶。",
  ),
  "牛乳": ExampleSentence(
    japanese: "学生は牛乳を飲む。",
    hiragana: "がくせいはぎゅうにゅうをのむ。",
    romaji: "gakusei wa gyuunyuu o nomu.",
    chinese: "學生喝牛奶。",
  ),
  "犬": ExampleSentence(
    japanese: "犬は家にいる。",
    hiragana: "いぬはいえにいる。",
    romaji: "inu wa ie ni iru.",
    chinese: "狗在家裡。",
  ),
  "猫": ExampleSentence(
    japanese: "猫は家にいる。",
    hiragana: "ねこはいえにいる。",
    romaji: "neko wa ie ni iru.",
    chinese: "貓在家裡。",
  ),
  "鳥": ExampleSentence(
    japanese: "鳥は空にいる。",
    hiragana: "とりはそらにいる。",
    romaji: "tori wa sora ni iru.",
    chinese: "鳥在天空。",
  ),
  "花": ExampleSentence(
    japanese: "子供は花を見る。",
    hiragana: "こどもははなをみる。",
    romaji: "kodomo wa hana o miru.",
    chinese: "小孩看花。",
  ),
  "木": ExampleSentence(
    japanese: "木は大きい。",
    hiragana: "きはおおきい。",
    romaji: "ki wa ookii.",
    chinese: "樹木很大。",
  ),
  "石": ExampleSentence(
    japanese: "子供は石を取る。",
    hiragana: "こどもはいしをとる。",
    romaji: "kodomo wa ishi o toru.",
    chinese: "小孩拿石頭。",
  ),
  "空": ExampleSentence(
    japanese: "空は青い。",
    hiragana: "そらはあおい。",
    romaji: "sora wa aoi.",
    chinese: "天空是藍色的。",
  ),
  "天気": ExampleSentence(
    japanese: "天気は良い。",
    hiragana: "てんきはよい。",
    romaji: "tenki wa yoi.",
    chinese: "天氣很好。",
  ),
  "雨": ExampleSentence(
    japanese: "今日は雨です。",
    hiragana: "きょうはあめです。",
    romaji: "kyou wa ame desu.",
    chinese: "今天下雨。",
  ),
  "雪": ExampleSentence(
    japanese: "今日は雪です。",
    hiragana: "きょうはゆきです。",
    romaji: "kyou wa yuki desu.",
    chinese: "今天下雪。",
  ),
  "風": ExampleSentence(
    japanese: "今日は風です。",
    hiragana: "きょうはかぜです。",
    romaji: "kyou wa kaze desu.",
    chinese: "今天有風。",
  ),
  "春": ExampleSentence(
    japanese: "春は良い。",
    hiragana: "はるはよい。",
    romaji: "haru wa yoi.",
    chinese: "春天很好。",
  ),
  "夏": ExampleSentence(
    japanese: "夏は暑い。",
    hiragana: "なつはあつい。",
    romaji: "natsu wa atsui.",
    chinese: "夏天很炎熱。",
  ),
  "秋": ExampleSentence(
    japanese: "秋は良い。",
    hiragana: "あきはよい。",
    romaji: "aki wa yoi.",
    chinese: "秋天很好。",
  ),
  "冬": ExampleSentence(
    japanese: "冬は寒い。",
    hiragana: "ふゆはさむい。",
    romaji: "fuyu wa samui.",
    chinese: "冬天很寒冷。",
  ),
  "朝": ExampleSentence(
    japanese: "学生は朝に起きる。",
    hiragana: "がくせいはあさにおきる。",
    romaji: "gakusei wa asa ni okiru.",
    chinese: "學生早晨起床。",
  ),
  "昼": ExampleSentence(
    japanese: "学生は昼にご飯を食べる。",
    hiragana: "がくせいはひるにごはんをたべる。",
    romaji: "gakusei wa hiru ni gohan o taberu.",
    chinese: "學生中午吃飯。",
  ),
  "夜": ExampleSentence(
    japanese: "学生は夜に本を読む。",
    hiragana: "がくせいはよるにほんをよむ。",
    romaji: "gakusei wa yoru ni hon o yomu.",
    chinese: "學生晚上讀書。",
  ),
  "時間": ExampleSentence(
    japanese: "時間は長い。",
    hiragana: "じかんはながい。",
    romaji: "jikan wa nagai.",
    chinese: "時間很長。",
  ),
  "分": ExampleSentence(
    japanese: "時間は分です。",
    hiragana: "じかんはふんです。",
    romaji: "jikan wa fun desu.",
    chinese: "時間是分鐘。",
  ),
  "秒": ExampleSentence(
    japanese: "時間は秒です。",
    hiragana: "じかんはびょうです。",
    romaji: "jikan wa byou desu.",
    chinese: "時間是秒。",
  ),
  "今日": ExampleSentence(
    japanese: "学生は今日本を読む。",
    hiragana: "がくせいはきょうほんをよむ。",
    romaji: "gakusei wa kyou hon o yomu.",
    chinese: "學生今天讀書。",
  ),
  "昨日": ExampleSentence(
    japanese: "昨日は休みです。",
    hiragana: "きのうはやすみです。",
    romaji: "kinou wa yasumi desu.",
    chinese: "昨天休假。",
  ),
  "明日": ExampleSentence(
    japanese: "学生は明日学校へ行く。",
    hiragana: "がくせいはあしたがっこうへいく。",
    romaji: "gakusei wa ashita gakkou e iku.",
    chinese: "學生明天去學校。",
  ),
  "週": ExampleSentence(
    japanese: "学生は週に学校へ行く。",
    hiragana: "がくせいはしゅうにがっこうへいく。",
    romaji: "gakusei wa shuu ni gakkou e iku.",
    chinese: "學生每週去學校。",
  ),
  "月": ExampleSentence(
    japanese: "月は空にある。",
    hiragana: "つきはそらにある。",
    romaji: "tsuki wa sora ni aru.",
    chinese: "月亮在天空。",
  ),
  "年": ExampleSentence(
    japanese: "年は時間です。",
    hiragana: "としはじかんです。",
    romaji: "toshi wa jikan desu.",
    chinese: "年是時間。",
  ),
  "誕生日": ExampleSentence(
    japanese: "今日は誕生日です。",
    hiragana: "きょうはたんじょうびです。",
    romaji: "kyou wa tanjoubi desu.",
    chinese: "今天是生日。",
  ),
  "休み": ExampleSentence(
    japanese: "今日は休みです。",
    hiragana: "きょうはやすみです。",
    romaji: "kyou wa yasumi desu.",
    chinese: "今天休假。",
  ),
  "試験": ExampleSentence(
    japanese: "試験は難しい。",
    hiragana: "しけんはむずかしい。",
    romaji: "shiken wa muzukashii.",
    chinese: "考試很困難。",
  ),
  "宿題": ExampleSentence(
    japanese: "学生は宿題を書く。",
    hiragana: "がくせいはしゅくだいをかく。",
    romaji: "gakusei wa shukudai o kaku.",
    chinese: "學生寫作業。",
  ),
  "質問": ExampleSentence(
    japanese: "学生は質問に答える。",
    hiragana: "がくせいはしつもんにこたえる。",
    romaji: "gakusei wa shitsumon ni kotaeru.",
    chinese: "學生回答問題。",
  ),
  "答え": ExampleSentence(
    japanese: "学生は答えを書く。",
    hiragana: "がくせいはこたえをかく。",
    romaji: "gakusei wa kotae o kaku.",
    chinese: "學生寫答案。",
  ),
  "漢字": ExampleSentence(
    japanese: "学生は漢字を書く。",
    hiragana: "がくせいはかんじをかく。",
    romaji: "gakusei wa kanji o kaku.",
    chinese: "學生寫漢字。",
  ),
  "言葉": ExampleSentence(
    japanese: "学生は言葉を覚える。",
    hiragana: "がくせいはことばをおぼえる。",
    romaji: "gakusei wa kotoba o oboeru.",
    chinese: "學生記住單字。",
  ),
  "文章": ExampleSentence(
    japanese: "学生は文章を読む。",
    hiragana: "がくせいはぶんしょうをよむ。",
    romaji: "gakusei wa bunshou o yomu.",
    chinese: "學生讀文章。",
  ),
  "名前": ExampleSentence(
    japanese: "学生は名前を書く。",
    hiragana: "がくせいはなまえをかく。",
    romaji: "gakusei wa namae o kaku.",
    chinese: "學生寫名字。",
  ),
  "住所": ExampleSentence(
    japanese: "学生は住所を書く。",
    hiragana: "がくせいはじゅうしょをかく。",
    romaji: "gakusei wa juusho o kaku.",
    chinese: "學生寫地址。",
  ),
  "住所録": ExampleSentence(
    japanese: "学生は住所録を見る。",
    hiragana: "がくせいはじゅうしょろくをみる。",
    romaji: "gakusei wa juushoroku o miru.",
    chinese: "學生看通訊錄。",
  ),
  "国": ExampleSentence(
    japanese: "学生は国へ行く。",
    hiragana: "がくせいはくにへいく。",
    romaji: "gakusei wa kuni e iku.",
    chinese: "學生去國家。",
  ),
  "音楽": ExampleSentence(
    japanese: "学生は音楽を聞く。",
    hiragana: "がくせいはおんがくをきく。",
    romaji: "gakusei wa ongaku o kiku.",
    chinese: "學生聽音樂。",
  ),
  "歌": ExampleSentence(
    japanese: "子供は歌を歌う。",
    hiragana: "こどもはうたをうたう。",
    romaji: "kodomo wa uta o utau.",
    chinese: "小孩唱歌。",
  ),
  "映画": ExampleSentence(
    japanese: "学生は映画を見る。",
    hiragana: "がくせいはえいがをみる。",
    romaji: "gakusei wa eiga o miru.",
    chinese: "學生看電影。",
  ),
  "写真": ExampleSentence(
    japanese: "学生は写真を撮る。",
    hiragana: "がくせいはしゃしんをとる。",
    romaji: "gakusei wa shashin o toru.",
    chinese: "學生拍照。",
  ),
  "絵": ExampleSentence(
    japanese: "子供は絵を見る。",
    hiragana: "こどもはえをみる。",
    romaji: "kodomo wa e o miru.",
    chinese: "小孩看圖畫。",
  ),
  "色": ExampleSentence(
    japanese: "花の色は赤い。",
    hiragana: "はなのいろはあかい。",
    romaji: "hana no iro wa akai.",
    chinese: "花的顏色是紅色的。",
  ),
  "赤": ExampleSentence(
    japanese: "花は赤です。",
    hiragana: "はなはあかです。",
    romaji: "hana wa aka desu.",
    chinese: "花是紅色。",
  ),
  "青": ExampleSentence(
    japanese: "空は青です。",
    hiragana: "そらはあおです。",
    romaji: "sora wa ao desu.",
    chinese: "天空是藍色。",
  ),
  "白": ExampleSentence(
    japanese: "雪は白です。",
    hiragana: "ゆきはしろです。",
    romaji: "yuki wa shiro desu.",
    chinese: "雪是白色。",
  ),
  "黒": ExampleSentence(
    japanese: "猫は黒です。",
    hiragana: "ねこはくろです。",
    romaji: "neko wa kuro desu.",
    chinese: "貓是黑色。",
  ),
  "緑": ExampleSentence(
    japanese: "木は緑です。",
    hiragana: "きはみどりです。",
    romaji: "ki wa midori desu.",
    chinese: "樹木是綠色。",
  ),
  "茶色": ExampleSentence(
    japanese: "鞄は茶色です。",
    hiragana: "かばんはちゃいろです。",
    romaji: "kaban wa chairo desu.",
    chinese: "包包是咖啡色。",
  ),
  "体": ExampleSentence(
    japanese: "子供は体が丈夫です。",
    hiragana: "こどもはからだがじょうぶです。",
    romaji: "kodomo wa karada ga joubu desu.",
    chinese: "小孩的身體很健康。",
  ),
  "頭": ExampleSentence(
    japanese: "子供は頭が大きい。",
    hiragana: "こどもはあたまがおおきい。",
    romaji: "kodomo wa atama ga ookii.",
    chinese: "小孩的頭很大。",
  ),
  "目": ExampleSentence(
    japanese: "学生は目で見る。",
    hiragana: "がくせいはめでみる。",
    romaji: "gakusei wa me de miru.",
    chinese: "學生用眼睛看。",
  ),
  "耳": ExampleSentence(
    japanese: "学生は耳で聞く。",
    hiragana: "がくせいはみみできく。",
    romaji: "gakusei wa mimi de kiku.",
    chinese: "學生用耳朵聽。",
  ),
  "口": ExampleSentence(
    japanese: "子供は口を開ける。",
    hiragana: "こどもはくちをあける。",
    romaji: "kodomo wa kuchi o akeru.",
    chinese: "小孩張開嘴巴。",
  ),
  "鼻": ExampleSentence(
    japanese: "子供は鼻を見る。",
    hiragana: "こどもははなをみる。",
    romaji: "kodomo wa hana o miru.",
    chinese: "小孩看鼻子。",
  ),
  "手": ExampleSentence(
    japanese: "子供は手で本を取る。",
    hiragana: "こどもはてでほんをとる。",
    romaji: "kodomo wa te de hon o toru.",
    chinese: "小孩用手拿書。",
  ),
  "足": ExampleSentence(
    japanese: "学生は足で歩く。",
    hiragana: "がくせいはあしであるく。",
    romaji: "gakusei wa ashi de aruku.",
    chinese: "學生用腳走路。",
  ),
  "顔": ExampleSentence(
    japanese: "学生は顔を見る。",
    hiragana: "がくせいはかおをみる。",
    romaji: "gakusei wa kao o miru.",
    chinese: "學生看臉。",
  ),
  "心": ExampleSentence(
    japanese: "子供は心が大きい。",
    hiragana: "こどもはこころがおおきい。",
    romaji: "kodomo wa kokoro ga ookii.",
    chinese: "小孩的心很大。",
  ),
  "病気": ExampleSentence(
    japanese: "父は病気です。",
    hiragana: "ちちはびょうきです。",
    romaji: "chichi wa byouki desu.",
    chinese: "父親生病。",
  ),
  "薬": ExampleSentence(
    japanese: "父は薬を飲む。",
    hiragana: "ちちはくすりをのむ。",
    romaji: "chichi wa kusuri o nomu.",
    chinese: "父親喝藥。",
  ),
  "運動": ExampleSentence(
    japanese: "先生は学生に運動を教える。",
    hiragana: "せんせいはがくせいにうんどうをおしえる。",
    romaji: "sensei wa gakusei ni undou o oshieru.",
    chinese: "老師教學生運動。",
  ),
  "旅行": ExampleSentence(
    japanese: "学生は旅行が楽しい。",
    hiragana: "がくせいはりょこうがたのしい。",
    romaji: "gakusei wa ryokou ga tanoshii.",
    chinese: "學生覺得旅行很快樂。",
  ),
  "地図": ExampleSentence(
    japanese: "学生は地図を見る。",
    hiragana: "がくせいはちずをみる。",
    romaji: "gakusei wa chizu o miru.",
    chinese: "學生看地圖。",
  ),
  "道具": ExampleSentence(
    japanese: "学生は道具を使う。",
    hiragana: "がくせいはどうぐをつかう。",
    romaji: "gakusei wa dougu o tsukau.",
    chinese: "學生使用工具。",
  ),
  "荷物": ExampleSentence(
    japanese: "学生は荷物を取る。",
    hiragana: "がくせいはにもつをとる。",
    romaji: "gakusei wa nimotsu o toru.",
    chinese: "學生拿行李。",
  ),
  "仕事": ExampleSentence(
    japanese: "仕事が終わる。",
    hiragana: "しごとがおわる。",
    romaji: "shigoto ga owaru.",
    chinese: "工作結束。",
  ),
  "家族": ExampleSentence(
    japanese: "部屋に家族がいる。",
    hiragana: "へやにかぞくがいる。",
    romaji: "heya ni kazoku ga iru.",
    chinese: "房間裡有家人。",
  ),
  "紙": ExampleSentence(
    japanese: "机に紙がある。",
    hiragana: "つくえにかみがある。",
    romaji: "tsukue ni kami ga aru.",
    chinese: "桌上有紙。",
  ),
  "鉛筆": ExampleSentence(
    japanese: "学生は鉛筆を使う。",
    hiragana: "がくせいはえんぴつをつかう。",
    romaji: "gakusei wa enpitsu o tsukau.",
    chinese: "學生使用鉛筆。",
  ),
  "手紙": ExampleSentence(
    japanese: "母は手紙を書く。",
    hiragana: "はははてがみをかく。",
    romaji: "haha wa tegami o kaku.",
    chinese: "母親寫信。",
  ),
  "切手": ExampleSentence(
    japanese: "母は切手を買う。",
    hiragana: "はははきってをかう。",
    romaji: "haha wa kitte o kau.",
    chinese: "母親買郵票。",
  ),
  "箱": ExampleSentence(
    japanese: "部屋に箱がある。",
    hiragana: "へやにはこがある。",
    romaji: "heya ni hako ga aru.",
    chinese: "房間裡有箱子。",
  ),
  "袋": ExampleSentence(
    japanese: "母は袋を買う。",
    hiragana: "はははふくろをかう。",
    romaji: "haha wa fukuro o kau.",
    chinese: "母親買袋子。",
  ),
  "コップ": ExampleSentence(
    japanese: "机にコップがある。",
    hiragana: "つくえにコップがある。",
    romaji: "tsukue ni koppu ga aru.",
    chinese: "桌上有杯子。",
  ),
  "皿": ExampleSentence(
    japanese: "母は皿を作る。",
    hiragana: "はははさらをつくる。",
    romaji: "haha wa sara o tsukuru.",
    chinese: "母親做盤子。",
  ),
  "塩": ExampleSentence(
    japanese: "母は塩を買う。",
    hiragana: "はははしおをかう。",
    romaji: "haha wa shio o kau.",
    chinese: "母親買鹽。",
  ),
  "砂糖": ExampleSentence(
    japanese: "母は砂糖を買う。",
    hiragana: "はははさとうをかう。",
    romaji: "haha wa satou o kau.",
    chinese: "母親買糖。",
  ),
  "パン": ExampleSentence(
    japanese: "子供はパンを食べる。",
    hiragana: "こどもはパンをたべる。",
    romaji: "kodomo wa pan o taberu.",
    chinese: "小孩吃麵包。",
  ),
  "牛肉": ExampleSentence(
    japanese: "父は牛肉を食べる。",
    hiragana: "ちちはぎゅうにくをたべる。",
    romaji: "chichi wa gyuuniku o taberu.",
    chinese: "父親吃牛肉。",
  ),
  "豚肉": ExampleSentence(
    japanese: "母は豚肉を買う。",
    hiragana: "はははぶたにくをかう。",
    romaji: "haha wa butaniku o kau.",
    chinese: "母親買豬肉。",
  ),
  "鶏肉": ExampleSentence(
    japanese: "子供は鶏肉を食べる。",
    hiragana: "こどもはとりにくをたべる。",
    romaji: "kodomo wa toriniku o taberu.",
    chinese: "小孩吃雞肉。",
  ),
  "りんご": ExampleSentence(
    japanese: "子供はりんごを食べる。",
    hiragana: "こどもはりんごをたべる。",
    romaji: "kodomo wa ringo o taberu.",
    chinese: "小孩吃蘋果。",
  ),
  "みかん": ExampleSentence(
    japanese: "子供はみかんを食べる。",
    hiragana: "こどもはみかんをたべる。",
    romaji: "kodomo wa mikan o taberu.",
    chinese: "小孩吃橘子。",
  ),
  "酒": ExampleSentence(
    japanese: "父は酒を飲む。",
    hiragana: "ちちはさけをのむ。",
    romaji: "chichi wa sake o nomu.",
    chinese: "父親喝酒。",
  ),
  "バス": ExampleSentence(
    japanese: "学生はバスで学校へ行く。",
    hiragana: "がくせいはバスでがっこうへいく。",
    romaji: "gakusei wa basu de gakkou e iku.",
    chinese: "學生坐公車去學校。",
  ),
  "地下鉄": ExampleSentence(
    japanese: "学生は地下鉄で駅へ行く。",
    hiragana: "がくせいはちかてつでえきへいく。",
    romaji: "gakusei wa chikatetsu de eki e iku.",
    chinese: "學生坐地鐵去車站。",
  ),
  "橋": ExampleSentence(
    japanese: "父は橋を歩く。",
    hiragana: "ちちははしをあるく。",
    romaji: "chichi wa hashi o aruku.",
    chinese: "父親走在橋上。",
  ),
  "角": ExampleSentence(
    japanese: "駅の角に店がある。",
    hiragana: "えきのかどにみせがある。",
    romaji: "eki no kado ni mise ga aru.",
    chinese: "車站轉角有商店。",
  ),
  "信号": ExampleSentence(
    japanese: "道に信号がある。",
    hiragana: "みちにしんごうがある。",
    romaji: "michi ni shingou ga aru.",
    chinese: "路上有紅綠燈。",
  ),
  "入口": ExampleSentence(
    japanese: "駅に入口がある。",
    hiragana: "えきにいりぐちがある。",
    romaji: "eki ni iriguchi ga aru.",
    chinese: "車站有入口。",
  ),
  "出口": ExampleSentence(
    japanese: "駅に出口がある。",
    hiragana: "えきにでぐちがある。",
    romaji: "eki ni deguchi ga aru.",
    chinese: "車站有出口。",
  ),
  "階段": ExampleSentence(
    japanese: "駅に階段がある。",
    hiragana: "えきにかいだんがある。",
    romaji: "eki ni kaidan ga aru.",
    chinese: "車站有樓梯。",
  ),
  "右": ExampleSentence(
    japanese: "学校の右に駅がある。",
    hiragana: "がっこうのみぎにえきがある。",
    romaji: "gakkou no migi ni eki ga aru.",
    chinese: "學校右邊有車站。",
  ),
  "左": ExampleSentence(
    japanese: "学校の左に銀行がある。",
    hiragana: "がっこうのひだりにぎんこうがある。",
    romaji: "gakkou no hidari ni ginkou ga aru.",
    chinese: "學校左邊有銀行。",
  ),
  "上": ExampleSentence(
    japanese: "机の上に本がある。",
    hiragana: "つくえのうえにほんがある。",
    romaji: "tsukue no ue ni hon ga aru.",
    chinese: "桌子上面有書。",
  ),
  "下": ExampleSentence(
    japanese: "机の下に猫がいる。",
    hiragana: "つくえのしたにねこがいる。",
    romaji: "tsukue no shita ni neko ga iru.",
    chinese: "桌子下面有貓。",
  ),
  "前": ExampleSentence(
    japanese: "駅の前に店がある。",
    hiragana: "えきのまえにみせがある。",
    romaji: "eki no mae ni mise ga aru.",
    chinese: "車站前面有商店。",
  ),
  "後ろ": ExampleSentence(
    japanese: "学校の後ろに公園がある。",
    hiragana: "がっこうのうしろにこうえんがある。",
    romaji: "gakkou no ushiro ni kouen ga aru.",
    chinese: "學校後面有公園。",
  ),
  "中": ExampleSentence(
    japanese: "部屋の中に本がある。",
    hiragana: "へやのなかにほんがある。",
    romaji: "heya no naka ni hon ga aru.",
    chinese: "房間裡面有書。",
  ),
  "外": ExampleSentence(
    japanese: "部屋の外に犬がいる。",
    hiragana: "へやのそとにいぬがいる。",
    romaji: "heya no soto ni inu ga iru.",
    chinese: "房間外面有狗。",
  ),
  "隣": ExampleSentence(
    japanese: "学校の隣に銀行がある。",
    hiragana: "がっこうのとなりにぎんこうがある。",
    romaji: "gakkou no tonari ni ginkou ga aru.",
    chinese: "學校旁邊有銀行。",
  ),
  "東": ExampleSentence(
    japanese: "学校の東に駅がある。",
    hiragana: "がっこうのひがしにえきがある。",
    romaji: "gakkou no higashi ni eki ga aru.",
    chinese: "學校東邊有車站。",
  ),
  "西": ExampleSentence(
    japanese: "学校の西に銀行がある。",
    hiragana: "がっこうのにしにぎんこうがある。",
    romaji: "gakkou no nishi ni ginkou ga aru.",
    chinese: "學校西邊有銀行。",
  ),
  "南": ExampleSentence(
    japanese: "学校の南に海がある。",
    hiragana: "がっこうのみなみにうみがある。",
    romaji: "gakkou no minami ni umi ga aru.",
    chinese: "學校南邊有海。",
  ),
  "北": ExampleSentence(
    japanese: "学校の北に山がある。",
    hiragana: "がっこうのきたにやまがある。",
    romaji: "gakkou no kita ni yama ga aru.",
    chinese: "學校北邊有山。",
  ),
  "日本": ExampleSentence(
    japanese: "母は日本へ行く。",
    hiragana: "はははにほんへいく。",
    romaji: "haha wa nihon e iku.",
    chinese: "母親去日本。",
  ),
  "日本語": ExampleSentence(
    japanese: "学生は日本語を読む。",
    hiragana: "がくせいはにほんごをよむ。",
    romaji: "gakusei wa nihongo o yomu.",
    chinese: "學生讀日文。",
  ),
  "英語": ExampleSentence(
    japanese: "学生は英語を話す。",
    hiragana: "がくせいはえいごをはなす。",
    romaji: "gakusei wa eigo o hanasu.",
    chinese: "學生說英文。",
  ),
  "意味": ExampleSentence(
    japanese: "先生は言葉の意味を言う。",
    hiragana: "せんせいはことばのいみをいう。",
    romaji: "sensei wa kotoba no imi o iu.",
    chinese: "老師說單字的意思。",
  ),
  "練習": ExampleSentence(
    japanese: "学生は漢字の練習をする。",
    hiragana: "がくせいはかんじのれんしゅうをする。",
    romaji: "gakusei wa kanji no renshuu o suru.",
    chinese: "學生練習漢字。",
  ),
  "授業": ExampleSentence(
    japanese: "今日授業がある。",
    hiragana: "きょうじゅぎょうがある。",
    romaji: "kyou jugyou ga aru.",
    chinese: "今天有課。",
  ),
  "教科書": ExampleSentence(
    japanese: "学生は教科書を読む。",
    hiragana: "がくせいはきょうかしょをよむ。",
    romaji: "gakusei wa kyoukasho o yomu.",
    chinese: "學生讀教科書。",
  ),
  "問題": ExampleSentence(
    japanese: "学生は問題を書く。",
    hiragana: "がくせいはもんだいをかく。",
    romaji: "gakusei wa mondai o kaku.",
    chinese: "學生寫題目。",
  ),
  "ラジオ": ExampleSentence(
    japanese: "部屋にラジオがある。",
    hiragana: "へやにラジオがある。",
    romaji: "heya ni rajio ga aru.",
    chinese: "房間裡有收音機。",
  ),
  "カメラ": ExampleSentence(
    japanese: "学生はカメラを使う。",
    hiragana: "がくせいはカメラをつかう。",
    romaji: "gakusei wa kamera o tsukau.",
    chinese: "學生使用照相機。",
  ),
  "眼鏡": ExampleSentence(
    japanese: "先生は眼鏡を使う。",
    hiragana: "せんせいはめがねをつかう。",
    romaji: "sensei wa megane o tsukau.",
    chinese: "老師使用眼鏡。",
  ),
  "上げる": ExampleSentence(
    japanese: "学生は手を上げる。",
    hiragana: "がくせいはてをあげる。",
    romaji: "gakusei wa te o ageru.",
    chinese: "學生舉手。",
  ),
  "洗う": ExampleSentence(
    japanese: "母は手を洗う。",
    hiragana: "はははてをあらう。",
    romaji: "haha wa te o arau.",
    chinese: "母親洗手。",
  ),
  "入れる": ExampleSentence(
    japanese: "学生は鞄に本を入れる。",
    hiragana: "がくせいはかばんにほんをいれる。",
    romaji: "gakusei wa kaban ni hon o ireru.",
    chinese: "學生把書放進包包。",
  ),
  "選ぶ": ExampleSentence(
    japanese: "学生は本を選ぶ。",
    hiragana: "がくせいはほんをえらぶ。",
    romaji: "gakusei wa hon o erabu.",
    chinese: "學生選書。",
  ),
  "泳ぐ": ExampleSentence(
    japanese: "子供は海で泳ぐ。",
    hiragana: "こどもはうみでおよぐ。",
    romaji: "kodomo wa umi de oyogu.",
    chinese: "小孩在海裡游泳。",
  ),
  "降りる": ExampleSentence(
    japanese: "学生は電車を降りる。",
    hiragana: "がくせいはでんしゃをおりる。",
    romaji: "gakusei wa densha o oriru.",
    chinese: "學生下電車。",
  ),
  "変わる": ExampleSentence(
    japanese: "天気が変わる。",
    hiragana: "てんきがかわる。",
    romaji: "tenki ga kawaru.",
    chinese: "天氣改變。",
  ),
  "考える": ExampleSentence(
    japanese: "学生は言葉を考える。",
    hiragana: "がくせいはことばをかんがえる。",
    romaji: "gakusei wa kotoba o kangaeru.",
    chinese: "學生思考單字。",
  ),
  "決める": ExampleSentence(
    japanese: "先生は答えを決める。",
    hiragana: "せんせいはこたえをきめる。",
    romaji: "sensei wa kotae o kimeru.",
    chinese: "老師決定答案。",
  ),
  "死ぬ": ExampleSentence(
    japanese: "魚が死ぬ。",
    hiragana: "さかながしぬ。",
    romaji: "sakana ga shinu.",
    chinese: "魚死了。",
  ),
  "閉める": ExampleSentence(
    japanese: "学生はドアを閉める。",
    hiragana: "がくせいはドアをしめる。",
    romaji: "gakusei wa doa o shimeru.",
    chinese: "學生關門。",
  ),
  "閉まる": ExampleSentence(
    japanese: "ドアが閉まる。",
    hiragana: "ドアがしまる。",
    romaji: "doa ga shimaru.",
    chinese: "門關好了。",
  ),
  "知る": ExampleSentence(
    japanese: "学生は名前を知る。",
    hiragana: "がくせいはなまえをしる。",
    romaji: "gakusei wa namae o shiru.",
    chinese: "學生知道名字。",
  ),
  "吸う": ExampleSentence(
    japanese: "父はたばこを吸う。",
    hiragana: "ちちはたばこをすう。",
    romaji: "chichi wa tabako o suu.",
    chinese: "父親吸菸。",
  ),
  "捨てる": ExampleSentence(
    japanese: "学生は紙を捨てる。",
    hiragana: "がくせいはかみをすてる。",
    romaji: "gakusei wa kami o suteru.",
    chinese: "學生丟紙。",
  ),
  "する": ExampleSentence(
    japanese: "学生は宿題をする。",
    hiragana: "がくせいはしゅくだいをする。",
    romaji: "gakusei wa shukudai o suru.",
    chinese: "學生做作業。",
  ),
  "違う": ExampleSentence(
    japanese: "答えが違う。",
    hiragana: "こたえがちがう。",
    romaji: "kotae ga chigau.",
    chinese: "答案不對。",
  ),
  "疲れる": ExampleSentence(
    japanese: "父が疲れる。",
    hiragana: "ちちがつかれる。",
    romaji: "chichi ga tsukareru.",
    chinese: "父親累了。",
  ),
  "着く": ExampleSentence(
    japanese: "学生は駅に着く。",
    hiragana: "がくせいはえきにつく。",
    romaji: "gakusei wa eki ni tsuku.",
    chinese: "學生抵達車站。",
  ),
  "出かける": ExampleSentence(
    japanese: "母は店へ出かける。",
    hiragana: "はははみせへでかける。",
    romaji: "haha wa mise e dekakeru.",
    chinese: "母親出門去商店。",
  ),
  "できる": ExampleSentence(
    japanese: "学生は漢字ができる。",
    hiragana: "がくせいはかんじができる。",
    romaji: "gakusei wa kanji ga dekiru.",
    chinese: "學生會漢字。",
  ),
  "通る": ExampleSentence(
    japanese: "学生は道を通る。",
    hiragana: "がくせいはみちをとおる。",
    romaji: "gakusei wa michi o tooru.",
    chinese: "學生通過道路。",
  ),
  "泊まる": ExampleSentence(
    japanese: "父はホテルに泊まる。",
    hiragana: "ちちはホテルにとまる。",
    romaji: "chichi wa hoteru ni tomaru.",
    chinese: "父親住飯店。",
  ),
  "止める": ExampleSentence(
    japanese: "学生は車を止める。",
    hiragana: "がくせいはくるまをとめる。",
    romaji: "gakusei wa kuruma o tomeru.",
    chinese: "學生把車停下。",
  ),
  "泣く": ExampleSentence(
    japanese: "子供が泣く。",
    hiragana: "こどもがなく。",
    romaji: "kodomo ga naku.",
    chinese: "小孩哭了。",
  ),
  "並ぶ": ExampleSentence(
    japanese: "学生は駅で並ぶ。",
    hiragana: "がくせいはえきでならぶ。",
    romaji: "gakusei wa eki de narabu.",
    chinese: "學生在車站排隊。",
  ),
  "なる": ExampleSentence(
    japanese: "子供は学生になる。",
    hiragana: "こどもはがくせいになる。",
    romaji: "kodomo wa gakusei ni naru.",
    chinese: "小孩成為學生。",
  ),
  "脱ぐ": ExampleSentence(
    japanese: "子供は靴を脱ぐ。",
    hiragana: "こどもはくつをぬぐ。",
    romaji: "kodomo wa kutsu o nugu.",
    chinese: "小孩脫鞋。",
  ),
  "寝る": ExampleSentence(
    japanese: "子供は部屋で寝る。",
    hiragana: "こどもはへやでねる。",
    romaji: "kodomo wa heya de neru.",
    chinese: "小孩在房間睡覺。",
  ),
  "登る": ExampleSentence(
    japanese: "父は山を登る。",
    hiragana: "ちちはやまをのぼる。",
    romaji: "chichi wa yama o noboru.",
    chinese: "父親爬山。",
  ),
  "乗る": ExampleSentence(
    japanese: "学生は電車に乗る。",
    hiragana: "がくせいはでんしゃにのる。",
    romaji: "gakusei wa densha ni noru.",
    chinese: "學生搭電車。",
  ),
  "始まる": ExampleSentence(
    japanese: "試験が始まる。",
    hiragana: "しけんがはじまる。",
    romaji: "shiken ga hajimaru.",
    chinese: "考試開始。",
  ),
  "始める": ExampleSentence(
    japanese: "学生は宿題を始める。",
    hiragana: "がくせいはしゅくだいをはじめる。",
    romaji: "gakusei wa shukudai o hajimeru.",
    chinese: "學生開始寫作業。",
  ),
  "走る": ExampleSentence(
    japanese: "子供は道を走る。",
    hiragana: "こどもはみちをはしる。",
    romaji: "kodomo wa michi o hashiru.",
    chinese: "小孩在路上跑。",
  ),
  "働く": ExampleSentence(
    japanese: "父は会社で働く。",
    hiragana: "ちちはかいしゃではたらく。",
    romaji: "chichi wa kaisha de hataraku.",
    chinese: "父親在公司做事。",
  ),
  "払う": ExampleSentence(
    japanese: "母はお金を払う。",
    hiragana: "はははおかねをはらう。",
    romaji: "haha wa okane o harau.",
    chinese: "母親付錢。",
  ),
  "降る": ExampleSentence(
    japanese: "雨が降る。",
    hiragana: "あめがふる。",
    romaji: "ame ga furu.",
    chinese: "下雨。",
  ),
  "見せる": ExampleSentence(
    japanese: "学生は写真を見せる。",
    hiragana: "がくせいはしゃしんをみせる。",
    romaji: "gakusei wa shashin o miseru.",
    chinese: "學生給人看照片。",
  ),
  "持つ": ExampleSentence(
    japanese: "学生は本を持つ。",
    hiragana: "がくせいはほんをもつ。",
    romaji: "gakusei wa hon o motsu.",
    chinese: "學生拿著書。",
  ),
  "休む": ExampleSentence(
    japanese: "父は家で休む。",
    hiragana: "ちちはいえでやすむ。",
    romaji: "chichi wa ie de yasumu.",
    chinese: "父親在家休息。",
  ),
  "呼ぶ": ExampleSentence(
    japanese: "母は子供を呼ぶ。",
    hiragana: "はははこどもをよぶ。",
    romaji: "haha wa kodomo o yobu.",
    chinese: "母親叫小孩。",
  ),
  "分かる": ExampleSentence(
    japanese: "学生は言葉が分かる。",
    hiragana: "がくせいはことばがわかる。",
    romaji: "gakusei wa kotoba ga wakaru.",
    chinese: "學生明白單字。",
  ),
  "忘れる": ExampleSentence(
    japanese: "学生は名前を忘れる。",
    hiragana: "がくせいはなまえをわすれる。",
    romaji: "gakusei wa namae o wasureru.",
    chinese: "學生忘記名字。",
  ),
  "思う": ExampleSentence(
    japanese: "母は子供を思う。",
    hiragana: "はははこどもをおもう。",
    romaji: "haha wa kodomo o omou.",
    chinese: "母親惦記小孩。",
  ),
  "掛ける": ExampleSentence(
    japanese: "母は電話を掛ける。",
    hiragana: "はははでんわをかける。",
    romaji: "haha wa denwa o kakeru.",
    chinese: "母親打電話。",
  ),
  "被る": ExampleSentence(
    japanese: "子供は帽子を被る。",
    hiragana: "こどもはぼうしをかぶる。",
    romaji: "kodomo wa boushi o kaburu.",
    chinese: "小孩戴帽子。",
  ),
  "履く": ExampleSentence(
    japanese: "子供は靴を履く。",
    hiragana: "こどもはくつをはく。",
    romaji: "kodomo wa kutsu o haku.",
    chinese: "小孩穿鞋。",
  ),
  "直す": ExampleSentence(
    japanese: "父は時計を直す。",
    hiragana: "ちちはとけいをなおす。",
    romaji: "chichi wa tokei o naosu.",
    chinese: "父親修時鐘。",
  ),
  "とても": ExampleSentence(
    japanese: "学生は本がとても面白い。",
    hiragana: "がくせいはほんがとてもおもしろい。",
    romaji: "gakusei wa hon ga totemo omoshiroi.",
    chinese: "學生覺得書非常有趣。",
  ),
  "いつも": ExampleSentence(
    japanese: "子供はいつも公園で遊ぶ。",
    hiragana: "こどもはいつもこうえんであそぶ。",
    romaji: "kodomo wa itsumo kouen de asobu.",
    chinese: "小孩總是在公園玩。",
  ),
  "よく": ExampleSentence(
    japanese: "学生は本をよく読む。",
    hiragana: "がくせいはほんをよくよむ。",
    romaji: "gakusei wa hon o yoku yomu.",
    chinese: "學生常常看書。",
  ),
  "もう": ExampleSentence(
    japanese: "父はもう家に帰る。",
    hiragana: "ちちはもういえにかえる。",
    romaji: "chichi wa mou ie ni kaeru.",
    chinese: "父親已經回家。",
  ),
  "まだ": ExampleSentence(
    japanese: "父はまだ仕事をしない。",
    hiragana: "ちちはまだしごとをしない。",
    romaji: "chichi wa mada shigoto o shinai.",
    chinese: "父親還沒工作。",
  ),
  "すぐ": ExampleSentence(
    japanese: "学生はすぐ学校へ行く。",
    hiragana: "がくせいはすぐがっこうへいく。",
    romaji: "gakusei wa sugu gakkou e iku.",
    chinese: "學生馬上去學校。",
  ),
  "時々": ExampleSentence(
    japanese: "父は時々新聞を読む。",
    hiragana: "ちちはときどきしんぶんをよむ。",
    romaji: "chichi wa tokidoki shinbun o yomu.",
    chinese: "父親有時候看報紙。",
  ),
  "たくさん": ExampleSentence(
    japanese: "母は果物をたくさん買う。",
    hiragana: "はははくだものをたくさんかう。",
    romaji: "haha wa kudamono o takusan kau.",
    chinese: "母親買很多水果。",
  ),
  "ちょっと": ExampleSentence(
    japanese: "学生は水をちょっと飲む。",
    hiragana: "がくせいはみずをちょっとのむ。",
    romaji: "gakusei wa mizu o chotto nomu.",
    chinese: "學生喝一點水。",
  ),
  "ゆっくり": ExampleSentence(
    japanese: "子供は道をゆっくり歩く。",
    hiragana: "こどもはみちをゆっくりあるく。",
    romaji: "kodomo wa michi o yukkuri aruku.",
    chinese: "小孩慢慢走路。",
  ),
  "一緒に": ExampleSentence(
    japanese: "学生は友達と一緒に行く。",
    hiragana: "がくせいはともだちといっしょにいく。",
    romaji: "gakusei wa tomodachi to isshoni iku.",
    chinese: "學生和朋友一起去。",
  ),
  "一番": ExampleSentence(
    japanese: "夏が一番暑い。",
    hiragana: "なつがいちばんあつい。",
    romaji: "natsu ga ichiban atsui.",
    chinese: "夏天最熱。",
  ),
  "もっと": ExampleSentence(
    japanese: "学生は本をもっと読む。",
    hiragana: "がくせいはほんをもっとよむ。",
    romaji: "gakusei wa hon o motto yomu.",
    chinese: "學生再多看一些書。",
  ),
  "あまり": ExampleSentence(
    japanese: "父は今日あまり仕事をしない。",
    hiragana: "ちちはきょうあまりしごとをしない。",
    romaji: "chichi wa kyou amari shigoto o shinai.",
    chinese: "父親今天不太工作。",
  ),
  "全然": ExampleSentence(
    japanese: "父は今日仕事を全然しない。",
    hiragana: "ちちはきょうしごとをぜんぜんしない。",
    romaji: "chichi wa kyou shigoto o zenzen shinai.",
    chinese: "父親今天完全不工作。",
  ),
  "少し": ExampleSentence(
    japanese: "学生は水を少し飲む。",
    hiragana: "がくせいはみずをすこしのむ。",
    romaji: "gakusei wa mizu o sukoshi nomu.",
    chinese: "學生喝少許水。",
  ),
  "多分": ExampleSentence(
    japanese: "明日は多分雨が降る。",
    hiragana: "あしたはたぶんあめがふる。",
    romaji: "ashita wa tabun ame ga furu.",
    chinese: "明天大概會下雨。",
  ),
  "初めて": ExampleSentence(
    japanese: "子供は初めて海を見る。",
    hiragana: "こどもははじめてうみをみる。",
    romaji: "kodomo wa hajimete umi o miru.",
    chinese: "小孩第一次看海。",
  ),
  "本当に": ExampleSentence(
    japanese: "映画は本当に面白い。",
    hiragana: "えいがはほんとうにおもしろい。",
    romaji: "eiga wa hontouni omoshiroi.",
    chinese: "電影真的有趣。",
  ),
  "もちろん": ExampleSentence(
    japanese: "学生はもちろん学校へ行く。",
    hiragana: "がくせいはもちろんがっこうへいく。",
    romaji: "gakusei wa mochiron gakkou e iku.",
    chinese: "學生當然去學校。",
  ),
  "ぜひ": ExampleSentence(
    japanese: "学生はぜひ日本へ行く。",
    hiragana: "がくせいはぜひにほんへいく。",
    romaji: "gakusei wa zehi nihon e iku.",
    chinese: "學生務必去日本。",
  ),
  "すっかり": ExampleSentence(
    japanese: "学生は言葉をすっかり忘れる。",
    hiragana: "がくせいはことばをすっかりわすれる。",
    romaji: "gakusei wa kotoba o sukkari wasureru.",
    chinese: "學生完全忘記單字。",
  ),
  "ちょうど": ExampleSentence(
    japanese: "学生はちょうど駅に着く。",
    hiragana: "がくせいはちょうどえきにつく。",
    romaji: "gakusei wa choudo eki ni tsuku.",
    chinese: "學生正好抵達車站。",
  ),
  "だんだん": ExampleSentence(
    japanese: "子供はだんだん日本語が分かる。",
    hiragana: "こどもはだんだんにほんごがわかる。",
    romaji: "kodomo wa dandan nihongo ga wakaru.",
    chinese: "小孩漸漸懂日文。",
  ),
  "どんどん": ExampleSentence(
    japanese: "子供はどんどん走る。",
    hiragana: "こどもはどんどんはしる。",
    romaji: "kodomo wa dondon hashiru.",
    chinese: "小孩不斷地跑。",
  ),
  "はっきり": ExampleSentence(
    japanese: "先生は言葉をはっきり言う。",
    hiragana: "せんせいはことばをはっきりいう。",
    romaji: "sensei wa kotoba o hakkiri iu.",
    chinese: "老師清楚地說單字。",
  ),
  "しっかり": ExampleSentence(
    japanese: "学生は本をしっかり持つ。",
    hiragana: "がくせいはほんをしっかりもつ。",
    romaji: "gakusei wa hon o shikkari motsu.",
    chinese: "學生把書拿好。",
  ),
  "ほとんど": ExampleSentence(
    japanese: "学生は言葉がほとんど分かる。",
    hiragana: "がくせいはことばがほとんどわかる。",
    romaji: "gakusei wa kotoba ga hotondo wakaru.",
    chinese: "學生幾乎都懂單字。",
  ),
  "必ず": ExampleSentence(
    japanese: "学生は必ず宿題をする。",
    hiragana: "がくせいはかならずしゅくだいをする。",
    romaji: "gakusei wa kanarazu shukudai o suru.",
    chinese: "學生一定寫作業。",
  ),
  "絶対": ExampleSentence(
    japanese: "学生は絶対学校へ行く。",
    hiragana: "がくせいはぜったいがっこうへいく。",
    romaji: "gakusei wa zettai gakkou e iku.",
    chinese: "學生絕對去學校。",
  ),
  "さっき": ExampleSentence(
    japanese: "母はさっき電話を掛ける。",
    hiragana: "はははさっきでんわをかける。",
    romaji: "haha wa sakki denwa o kakeru.",
    chinese: "母親剛才打電話。",
  ),
  "先に": ExampleSentence(
    japanese: "学生は先に学校へ行く。",
    hiragana: "がくせいはさきにがっこうへいく。",
    romaji: "gakusei wa sakini gakkou e iku.",
    chinese: "學生先去學校。",
  ),
  "後で": ExampleSentence(
    japanese: "学生は後で本を読む。",
    hiragana: "がくせいはあとでほんをよむ。",
    romaji: "gakusei wa atode hon o yomu.",
    chinese: "學生稍後看書。",
  ),
};
