import 'package:shared_preferences/shared_preferences.dart';

const String kanaFavoritesKey = 'kanaFavorites';

class KanaCard {
  KanaCard({
    required this.kana,
    required this.romaji,
    required this.example,
    required this.exampleRomaji,
    required this.exampleChinese,
    this.isFavorite = false,
  });

  final String kana;
  final String romaji;
  final String example;
  final String exampleRomaji;
  final String exampleChinese;
  bool isFavorite;
}

class _KanaSpec {
  const _KanaSpec({
    required this.hiragana,
    required this.romaji,
    required this.hiraganaExample,
    required this.hiraganaExampleRomaji,
    required this.hiraganaExampleChinese,
    required this.katakanaExample,
    required this.katakanaExampleRomaji,
    required this.katakanaExampleChinese,
  });

  final String hiragana;
  final String romaji;
  final String hiraganaExample;
  final String hiraganaExampleRomaji;
  final String hiraganaExampleChinese;
  final String katakanaExample;
  final String katakanaExampleRomaji;
  final String katakanaExampleChinese;
}

String katakanaFor(String hiragana) {
  return String.fromCharCodes(
    hiragana.runes.map((rune) {
      if (rune >= 0x3041 && rune <= 0x3096) return rune + 0x60;
      return rune;
    }),
  );
}

const List<_KanaSpec> _specs = [
  _KanaSpec(
    hiragana: 'あ',
    romaji: 'a',
    hiraganaExample: 'あめ',
    hiraganaExampleRomaji: 'ame',
    hiraganaExampleChinese: '雨',
    katakanaExample: 'アイス',
    katakanaExampleRomaji: 'aisu',
    katakanaExampleChinese: '冰淇淋',
  ),
  _KanaSpec(
    hiragana: 'い',
    romaji: 'i',
    hiraganaExample: 'いぬ',
    hiraganaExampleRomaji: 'inu',
    hiraganaExampleChinese: '狗',
    katakanaExample: 'イギリス',
    katakanaExampleRomaji: 'igirisu',
    katakanaExampleChinese: '英國',
  ),
  _KanaSpec(
    hiragana: 'う',
    romaji: 'u',
    hiraganaExample: 'うみ',
    hiraganaExampleRomaji: 'umi',
    hiraganaExampleChinese: '海',
    katakanaExample: 'ウール',
    katakanaExampleRomaji: 'uuru',
    katakanaExampleChinese: '羊毛',
  ),
  _KanaSpec(
    hiragana: 'え',
    romaji: 'e',
    hiraganaExample: 'えき',
    hiraganaExampleRomaji: 'eki',
    hiraganaExampleChinese: '車站',
    katakanaExample: 'エレベーター',
    katakanaExampleRomaji: 'erebeetaa',
    katakanaExampleChinese: '電梯',
  ),
  _KanaSpec(
    hiragana: 'お',
    romaji: 'o',
    hiraganaExample: 'おちゃ',
    hiraganaExampleRomaji: 'ocha',
    hiraganaExampleChinese: '茶',
    katakanaExample: 'オレンジ',
    katakanaExampleRomaji: 'orenji',
    katakanaExampleChinese: '柳橙',
  ),
  _KanaSpec(
    hiragana: 'か',
    romaji: 'ka',
    hiraganaExample: 'かさ',
    hiraganaExampleRomaji: 'kasa',
    hiraganaExampleChinese: '傘',
    katakanaExample: 'カメラ',
    katakanaExampleRomaji: 'kamera',
    katakanaExampleChinese: '相機',
  ),
  _KanaSpec(
    hiragana: 'き',
    romaji: 'ki',
    hiraganaExample: 'きた',
    hiraganaExampleRomaji: 'kita',
    hiraganaExampleChinese: '北',
    katakanaExample: 'キロ',
    katakanaExampleRomaji: 'kiro',
    katakanaExampleChinese: '公里',
  ),
  _KanaSpec(
    hiragana: 'く',
    romaji: 'ku',
    hiraganaExample: 'くち',
    hiraganaExampleRomaji: 'kuchi',
    hiraganaExampleChinese: '嘴巴',
    katakanaExample: 'クラス',
    katakanaExampleRomaji: 'kurasu',
    katakanaExampleChinese: '班級',
  ),
  _KanaSpec(
    hiragana: 'け',
    romaji: 'ke',
    hiraganaExample: 'けむり',
    hiraganaExampleRomaji: 'kemuri',
    hiraganaExampleChinese: '煙',
    katakanaExample: 'ケーキ',
    katakanaExampleRomaji: 'keeki',
    katakanaExampleChinese: '蛋糕',
  ),
  _KanaSpec(
    hiragana: 'こ',
    romaji: 'ko',
    hiraganaExample: 'ここ',
    hiraganaExampleRomaji: 'koko',
    hiraganaExampleChinese: '這裡',
    katakanaExample: 'コーヒー',
    katakanaExampleRomaji: 'koohii',
    katakanaExampleChinese: '咖啡',
  ),
  _KanaSpec(
    hiragana: 'さ',
    romaji: 'sa',
    hiraganaExample: 'さかな',
    hiraganaExampleRomaji: 'sakana',
    hiraganaExampleChinese: '魚',
    katakanaExample: 'サラダ',
    katakanaExampleRomaji: 'sarada',
    katakanaExampleChinese: '沙拉',
  ),
  _KanaSpec(
    hiragana: 'し',
    romaji: 'shi',
    hiraganaExample: 'しま',
    hiraganaExampleRomaji: 'shima',
    hiraganaExampleChinese: '島',
    katakanaExample: 'シャツ',
    katakanaExampleRomaji: 'shatsu',
    katakanaExampleChinese: '襯衫',
  ),
  _KanaSpec(
    hiragana: 'す',
    romaji: 'su',
    hiraganaExample: 'すし',
    hiraganaExampleRomaji: 'sushi',
    hiraganaExampleChinese: '壽司',
    katakanaExample: 'スプーン',
    katakanaExampleRomaji: 'supuun',
    katakanaExampleChinese: '湯匙',
  ),
  _KanaSpec(
    hiragana: 'せ',
    romaji: 'se',
    hiraganaExample: 'せなか',
    hiraganaExampleRomaji: 'senaka',
    hiraganaExampleChinese: '背',
    katakanaExample: 'セーター',
    katakanaExampleRomaji: 'seetaa',
    katakanaExampleChinese: '毛衣',
  ),
  _KanaSpec(
    hiragana: 'そ',
    romaji: 'so',
    hiraganaExample: 'そら',
    hiraganaExampleRomaji: 'sora',
    hiraganaExampleChinese: '天空',
    katakanaExample: 'ソーダ',
    katakanaExampleRomaji: 'sooda',
    katakanaExampleChinese: '汽水',
  ),
  _KanaSpec(
    hiragana: 'た',
    romaji: 'ta',
    hiraganaExample: 'たまご',
    hiraganaExampleRomaji: 'tamago',
    hiraganaExampleChinese: '雞蛋',
    katakanaExample: 'タクシー',
    katakanaExampleRomaji: 'takushii',
    katakanaExampleChinese: '計程車',
  ),
  _KanaSpec(
    hiragana: 'ち',
    romaji: 'chi',
    hiraganaExample: 'ちず',
    hiraganaExampleRomaji: 'chizu',
    hiraganaExampleChinese: '地圖',
    katakanaExample: 'チーズ',
    katakanaExampleRomaji: 'chiizu',
    katakanaExampleChinese: '起司',
  ),
  _KanaSpec(
    hiragana: 'つ',
    romaji: 'tsu',
    hiraganaExample: 'つき',
    hiraganaExampleRomaji: 'tsuki',
    hiraganaExampleChinese: '月亮',
    katakanaExample: 'ツナ',
    katakanaExampleRomaji: 'tsuna',
    katakanaExampleChinese: '鮪魚',
  ),
  _KanaSpec(
    hiragana: 'て',
    romaji: 'te',
    hiraganaExample: 'てがみ',
    hiraganaExampleRomaji: 'tegami',
    hiraganaExampleChinese: '信',
    katakanaExample: 'テレビ',
    katakanaExampleRomaji: 'terebi',
    katakanaExampleChinese: '電視',
  ),
  _KanaSpec(
    hiragana: 'と',
    romaji: 'to',
    hiraganaExample: 'とり',
    hiraganaExampleRomaji: 'tori',
    hiraganaExampleChinese: '鳥',
    katakanaExample: 'トマト',
    katakanaExampleRomaji: 'tomato',
    katakanaExampleChinese: '番茄',
  ),
  _KanaSpec(
    hiragana: 'な',
    romaji: 'na',
    hiraganaExample: 'なつ',
    hiraganaExampleRomaji: 'natsu',
    hiraganaExampleChinese: '夏天',
    katakanaExample: 'ナイフ',
    katakanaExampleRomaji: 'naifu',
    katakanaExampleChinese: '刀子',
  ),
  _KanaSpec(
    hiragana: 'に',
    romaji: 'ni',
    hiraganaExample: 'にく',
    hiraganaExampleRomaji: 'niku',
    hiraganaExampleChinese: '肉',
    katakanaExample: 'ニュース',
    katakanaExampleRomaji: 'nyuusu',
    katakanaExampleChinese: '新聞',
  ),
  _KanaSpec(
    hiragana: 'ぬ',
    romaji: 'nu',
    hiraganaExample: 'ぬの',
    hiraganaExampleRomaji: 'nuno',
    hiraganaExampleChinese: '布',
    katakanaExample: 'ヌードル',
    katakanaExampleRomaji: 'nuudoru',
    katakanaExampleChinese: '麵',
  ),
  _KanaSpec(
    hiragana: 'ね',
    romaji: 'ne',
    hiraganaExample: 'ねこ',
    hiraganaExampleRomaji: 'neko',
    hiraganaExampleChinese: '貓',
    katakanaExample: 'ネックレス',
    katakanaExampleRomaji: 'nekkuresu',
    katakanaExampleChinese: '項鍊',
  ),
  _KanaSpec(
    hiragana: 'の',
    romaji: 'no',
    hiraganaExample: 'のり',
    hiraganaExampleRomaji: 'nori',
    hiraganaExampleChinese: '海苔',
    katakanaExample: 'ノート',
    katakanaExampleRomaji: 'nooto',
    katakanaExampleChinese: '筆記本',
  ),
  _KanaSpec(
    hiragana: 'は',
    romaji: 'ha',
    hiraganaExample: 'はな',
    hiraganaExampleRomaji: 'hana',
    hiraganaExampleChinese: '花',
    katakanaExample: 'ハンカチ',
    katakanaExampleRomaji: 'hankachi',
    katakanaExampleChinese: '手帕',
  ),
  _KanaSpec(
    hiragana: 'ひ',
    romaji: 'hi',
    hiraganaExample: 'ひと',
    hiraganaExampleRomaji: 'hito',
    hiraganaExampleChinese: '人',
    katakanaExample: 'ヒーロー',
    katakanaExampleRomaji: 'hiiroo',
    katakanaExampleChinese: '英雄',
  ),
  _KanaSpec(
    hiragana: 'ふ',
    romaji: 'fu',
    hiraganaExample: 'ふね',
    hiraganaExampleRomaji: 'fune',
    hiraganaExampleChinese: '船',
    katakanaExample: 'フランス',
    katakanaExampleRomaji: 'furansu',
    katakanaExampleChinese: '法國',
  ),
  _KanaSpec(
    hiragana: 'へ',
    romaji: 'he',
    hiraganaExample: 'へや',
    hiraganaExampleRomaji: 'heya',
    hiraganaExampleChinese: '房間',
    katakanaExample: 'ヘリコプター',
    katakanaExampleRomaji: 'herikoputaa',
    katakanaExampleChinese: '直升機',
  ),
  _KanaSpec(
    hiragana: 'ほ',
    romaji: 'ho',
    hiraganaExample: 'ほし',
    hiraganaExampleRomaji: 'hoshi',
    hiraganaExampleChinese: '星星',
    katakanaExample: 'ホテル',
    katakanaExampleRomaji: 'hoteru',
    katakanaExampleChinese: '飯店',
  ),
  _KanaSpec(
    hiragana: 'ま',
    romaji: 'ma',
    hiraganaExample: 'まど',
    hiraganaExampleRomaji: 'mado',
    hiraganaExampleChinese: '窗戶',
    katakanaExample: 'マスク',
    katakanaExampleRomaji: 'masuku',
    katakanaExampleChinese: '口罩',
  ),
  _KanaSpec(
    hiragana: 'み',
    romaji: 'mi',
    hiraganaExample: 'みず',
    hiraganaExampleRomaji: 'mizu',
    hiraganaExampleChinese: '水',
    katakanaExample: 'ミルク',
    katakanaExampleRomaji: 'miruku',
    katakanaExampleChinese: '牛奶',
  ),
  _KanaSpec(
    hiragana: 'む',
    romaji: 'mu',
    hiraganaExample: 'むし',
    hiraganaExampleRomaji: 'mushi',
    hiraganaExampleChinese: '蟲',
    katakanaExample: 'ムード',
    katakanaExampleRomaji: 'muudo',
    katakanaExampleChinese: '氣氛',
  ),
  _KanaSpec(
    hiragana: 'め',
    romaji: 'me',
    hiraganaExample: 'めがね',
    hiraganaExampleRomaji: 'megane',
    hiraganaExampleChinese: '眼鏡',
    katakanaExample: 'メニュー',
    katakanaExampleRomaji: 'menyuu',
    katakanaExampleChinese: '菜單',
  ),
  _KanaSpec(
    hiragana: 'も',
    romaji: 'mo',
    hiraganaExample: 'もも',
    hiraganaExampleRomaji: 'momo',
    hiraganaExampleChinese: '桃子',
    katakanaExample: 'モーター',
    katakanaExampleRomaji: 'mootaa',
    katakanaExampleChinese: '馬達',
  ),
  _KanaSpec(
    hiragana: 'や',
    romaji: 'ya',
    hiraganaExample: 'やま',
    hiraganaExampleRomaji: 'yama',
    hiraganaExampleChinese: '山',
    katakanaExample: 'ヤシ',
    katakanaExampleRomaji: 'yashi',
    katakanaExampleChinese: '椰子',
  ),
  _KanaSpec(
    hiragana: 'ゆ',
    romaji: 'yu',
    hiraganaExample: 'ゆき',
    hiraganaExampleRomaji: 'yuki',
    hiraganaExampleChinese: '雪',
    katakanaExample: 'ユーモア',
    katakanaExampleRomaji: 'yuumoa',
    katakanaExampleChinese: '幽默',
  ),
  _KanaSpec(
    hiragana: 'よ',
    romaji: 'yo',
    hiraganaExample: 'よる',
    hiraganaExampleRomaji: 'yoru',
    hiraganaExampleChinese: '夜晚',
    katakanaExample: 'ヨーグルト',
    katakanaExampleRomaji: 'yooguruto',
    katakanaExampleChinese: '優格',
  ),
  _KanaSpec(
    hiragana: 'ら',
    romaji: 'ra',
    hiraganaExample: 'らくだ',
    hiraganaExampleRomaji: 'rakuda',
    hiraganaExampleChinese: '駱駝',
    katakanaExample: 'ラジオ',
    katakanaExampleRomaji: 'rajio',
    katakanaExampleChinese: '收音機',
  ),
  _KanaSpec(
    hiragana: 'り',
    romaji: 'ri',
    hiraganaExample: 'りす',
    hiraganaExampleRomaji: 'risu',
    hiraganaExampleChinese: '松鼠',
    katakanaExample: 'リモコン',
    katakanaExampleRomaji: 'rimokon',
    katakanaExampleChinese: '遙控器',
  ),
  _KanaSpec(
    hiragana: 'る',
    romaji: 'ru',
    hiraganaExample: 'るす',
    hiraganaExampleRomaji: 'rusu',
    hiraganaExampleChinese: '不在',
    katakanaExample: 'ルール',
    katakanaExampleRomaji: 'ruuru',
    katakanaExampleChinese: '規則',
  ),
  _KanaSpec(
    hiragana: 'れ',
    romaji: 're',
    hiraganaExample: 'れきし',
    hiraganaExampleRomaji: 'rekishi',
    hiraganaExampleChinese: '歷史',
    katakanaExample: 'レモン',
    katakanaExampleRomaji: 'remon',
    katakanaExampleChinese: '檸檬',
  ),
  _KanaSpec(
    hiragana: 'ろ',
    romaji: 'ro',
    hiraganaExample: 'ろく',
    hiraganaExampleRomaji: 'roku',
    hiraganaExampleChinese: '六',
    katakanaExample: 'ロープ',
    katakanaExampleRomaji: 'roopu',
    katakanaExampleChinese: '繩子',
  ),
  _KanaSpec(
    hiragana: 'わ',
    romaji: 'wa',
    hiraganaExample: 'わに',
    hiraganaExampleRomaji: 'wani',
    hiraganaExampleChinese: '鱷魚',
    katakanaExample: 'ワイン',
    katakanaExampleRomaji: 'wain',
    katakanaExampleChinese: '葡萄酒',
  ),
  _KanaSpec(
    hiragana: 'を',
    romaji: 'wo',
    hiraganaExample: 'みずをのむ',
    hiraganaExampleRomaji: 'mizuwonomu',
    hiraganaExampleChinese: '喝水',
    katakanaExample: 'テヲアラウ',
    katakanaExampleRomaji: 'tewoarau',
    katakanaExampleChinese: '洗手',
  ),
  _KanaSpec(
    hiragana: 'ん',
    romaji: 'n',
    hiraganaExample: 'ほん',
    hiraganaExampleRomaji: 'hon',
    hiraganaExampleChinese: '書',
    katakanaExample: 'パン',
    katakanaExampleRomaji: 'pan',
    katakanaExampleChinese: '麵包',
  ),
  _KanaSpec(
    hiragana: 'が',
    romaji: 'ga',
    hiraganaExample: 'がっこう',
    hiraganaExampleRomaji: 'gakkou',
    hiraganaExampleChinese: '學校',
    katakanaExample: 'ガス',
    katakanaExampleRomaji: 'gasu',
    katakanaExampleChinese: '瓦斯',
  ),
  _KanaSpec(
    hiragana: 'ぎ',
    romaji: 'gi',
    hiraganaExample: 'ぎんこう',
    hiraganaExampleRomaji: 'ginkou',
    hiraganaExampleChinese: '銀行',
    katakanaExample: 'ギター',
    katakanaExampleRomaji: 'gitaa',
    katakanaExampleChinese: '吉他',
  ),
  _KanaSpec(
    hiragana: 'ぐ',
    romaji: 'gu',
    hiraganaExample: 'ぐあい',
    hiraganaExampleRomaji: 'guai',
    hiraganaExampleChinese: '情況',
    katakanaExample: 'グラス',
    katakanaExampleRomaji: 'gurasu',
    katakanaExampleChinese: '玻璃杯',
  ),
  _KanaSpec(
    hiragana: 'げ',
    romaji: 'ge',
    hiraganaExample: 'げんき',
    hiraganaExampleRomaji: 'genki',
    hiraganaExampleChinese: '有精神',
    katakanaExample: 'ゲーム',
    katakanaExampleRomaji: 'geemu',
    katakanaExampleChinese: '遊戲',
  ),
  _KanaSpec(
    hiragana: 'ご',
    romaji: 'go',
    hiraganaExample: 'ごはん',
    hiraganaExampleRomaji: 'gohan',
    hiraganaExampleChinese: '飯',
    katakanaExample: 'ゴルフ',
    katakanaExampleRomaji: 'gorufu',
    katakanaExampleChinese: '高爾夫',
  ),
  _KanaSpec(
    hiragana: 'ざ',
    romaji: 'za',
    hiraganaExample: 'ざっし',
    hiraganaExampleRomaji: 'zasshi',
    hiraganaExampleChinese: '雜誌',
    katakanaExample: 'ザブトン',
    katakanaExampleRomaji: 'zabuton',
    katakanaExampleChinese: '坐墊',
  ),
  _KanaSpec(
    hiragana: 'じ',
    romaji: 'ji',
    hiraganaExample: 'じかん',
    hiraganaExampleRomaji: 'jikan',
    hiraganaExampleChinese: '時間',
    katakanaExample: 'ジュース',
    katakanaExampleRomaji: 'juusu',
    katakanaExampleChinese: '果汁',
  ),
  _KanaSpec(
    hiragana: 'ず',
    romaji: 'zu',
    hiraganaExample: 'ずぼん',
    hiraganaExampleRomaji: 'zubon',
    hiraganaExampleChinese: '褲子',
    katakanaExample: 'ズボン',
    katakanaExampleRomaji: 'zubon',
    katakanaExampleChinese: '褲子',
  ),
  _KanaSpec(
    hiragana: 'ぜ',
    romaji: 'ze',
    hiraganaExample: 'ぜんぶ',
    hiraganaExampleRomaji: 'zenbu',
    hiraganaExampleChinese: '全部',
    katakanaExample: 'ゼロ',
    katakanaExampleRomaji: 'zero',
    katakanaExampleChinese: '零',
  ),
  _KanaSpec(
    hiragana: 'ぞ',
    romaji: 'zo',
    hiraganaExample: 'ぞう',
    hiraganaExampleRomaji: 'zou',
    hiraganaExampleChinese: '大象',
    katakanaExample: 'ゾーン',
    katakanaExampleRomaji: 'zoon',
    katakanaExampleChinese: '區域',
  ),
  _KanaSpec(
    hiragana: 'だ',
    romaji: 'da',
    hiraganaExample: 'だいがく',
    hiraganaExampleRomaji: 'daigaku',
    hiraganaExampleChinese: '大學',
    katakanaExample: 'ダンス',
    katakanaExampleRomaji: 'dansu',
    katakanaExampleChinese: '舞蹈',
  ),
  _KanaSpec(
    hiragana: 'ぢ',
    romaji: 'di',
    hiraganaExample: 'はなぢ',
    hiraganaExampleRomaji: 'hanadi',
    hiraganaExampleChinese: '鼻血',
    katakanaExample: 'チヂミ',
    katakanaExampleRomaji: 'chidimi',
    katakanaExampleChinese: '韓式煎餅',
  ),
  _KanaSpec(
    hiragana: 'づ',
    romaji: 'du',
    hiraganaExample: 'つづく',
    hiraganaExampleRomaji: 'tsuduku',
    hiraganaExampleChinese: '持續',
    katakanaExample: 'カンヅメ',
    katakanaExampleRomaji: 'kandume',
    katakanaExampleChinese: '罐頭',
  ),
  _KanaSpec(
    hiragana: 'で',
    romaji: 'de',
    hiraganaExample: 'でんわ',
    hiraganaExampleRomaji: 'denwa',
    hiraganaExampleChinese: '電話',
    katakanaExample: 'デパート',
    katakanaExampleRomaji: 'depaato',
    katakanaExampleChinese: '百貨公司',
  ),
  _KanaSpec(
    hiragana: 'ど',
    romaji: 'do',
    hiraganaExample: 'どこ',
    hiraganaExampleRomaji: 'doko',
    hiraganaExampleChinese: '哪裡',
    katakanaExample: 'ドア',
    katakanaExampleRomaji: 'doa',
    katakanaExampleChinese: '門',
  ),
  _KanaSpec(
    hiragana: 'ば',
    romaji: 'ba',
    hiraganaExample: 'ばんごはん',
    hiraganaExampleRomaji: 'bangohan',
    hiraganaExampleChinese: '晚飯',
    katakanaExample: 'バス',
    katakanaExampleRomaji: 'basu',
    katakanaExampleChinese: '公車',
  ),
  _KanaSpec(
    hiragana: 'び',
    romaji: 'bi',
    hiraganaExample: 'びん',
    hiraganaExampleRomaji: 'bin',
    hiraganaExampleChinese: '瓶子',
    katakanaExample: 'ビデオ',
    katakanaExampleRomaji: 'bideo',
    katakanaExampleChinese: '影片',
  ),
  _KanaSpec(
    hiragana: 'ぶ',
    romaji: 'bu',
    hiraganaExample: 'ぶた',
    hiraganaExampleRomaji: 'buta',
    hiraganaExampleChinese: '豬',
    katakanaExample: 'ブーツ',
    katakanaExampleRomaji: 'buutsu',
    katakanaExampleChinese: '靴子',
  ),
  _KanaSpec(
    hiragana: 'べ',
    romaji: 'be',
    hiraganaExample: 'べんきょう',
    hiraganaExampleRomaji: 'benkyou',
    hiraganaExampleChinese: '學習',
    katakanaExample: 'ベッド',
    katakanaExampleRomaji: 'beddo',
    katakanaExampleChinese: '床',
  ),
  _KanaSpec(
    hiragana: 'ぼ',
    romaji: 'bo',
    hiraganaExample: 'ぼうし',
    hiraganaExampleRomaji: 'boushi',
    hiraganaExampleChinese: '帽子',
    katakanaExample: 'ボール',
    katakanaExampleRomaji: 'booru',
    katakanaExampleChinese: '球',
  ),
  _KanaSpec(
    hiragana: 'ぱ',
    romaji: 'pa',
    hiraganaExample: 'かっぱ',
    hiraganaExampleRomaji: 'kappa',
    hiraganaExampleChinese: '河童',
    katakanaExample: 'パン',
    katakanaExampleRomaji: 'pan',
    katakanaExampleChinese: '麵包',
  ),
  _KanaSpec(
    hiragana: 'ぴ',
    romaji: 'pi',
    hiraganaExample: 'えんぴつ',
    hiraganaExampleRomaji: 'enpitsu',
    hiraganaExampleChinese: '鉛筆',
    katakanaExample: 'ピアノ',
    katakanaExampleRomaji: 'piano',
    katakanaExampleChinese: '鋼琴',
  ),
  _KanaSpec(
    hiragana: 'ぷ',
    romaji: 'pu',
    hiraganaExample: 'きっぷ',
    hiraganaExampleRomaji: 'kippu',
    hiraganaExampleChinese: '票',
    katakanaExample: 'プール',
    katakanaExampleRomaji: 'puuru',
    katakanaExampleChinese: '游泳池',
  ),
  _KanaSpec(
    hiragana: 'ぺ',
    romaji: 'pe',
    hiraganaExample: 'ぺらぺら',
    hiraganaExampleRomaji: 'perapera',
    hiraganaExampleChinese: '流利',
    katakanaExample: 'ペン',
    katakanaExampleRomaji: 'pen',
    katakanaExampleChinese: '筆',
  ),
  _KanaSpec(
    hiragana: 'ぽ',
    romaji: 'po',
    hiraganaExample: 'さんぽ',
    hiraganaExampleRomaji: 'sanpo',
    hiraganaExampleChinese: '散步',
    katakanaExample: 'ポスト',
    katakanaExampleRomaji: 'posuto',
    katakanaExampleChinese: '郵筒',
  ),
];

final List<KanaCard> hiraganaCards = [
  for (final spec in _specs)
    KanaCard(
      kana: spec.hiragana,
      romaji: spec.romaji,
      example: spec.hiraganaExample,
      exampleRomaji: spec.hiraganaExampleRomaji,
      exampleChinese: spec.hiraganaExampleChinese,
    ),
];

final List<KanaCard> katakanaCards = [
  for (final spec in _specs)
    KanaCard(
      kana: katakanaFor(spec.hiragana),
      romaji: spec.romaji,
      example: spec.katakanaExample,
      exampleRomaji: spec.katakanaExampleRomaji,
      exampleChinese: spec.katakanaExampleChinese,
    ),
];

List<KanaCard> get allKanaCards => [...hiraganaCards, ...katakanaCards];

List<KanaCard> get favoriteKanaCards =>
    allKanaCards.where((card) => card.isFavorite).toList();

Future<void> loadKanaFavorites() async {
  final prefs = await SharedPreferences.getInstance();
  final saved = prefs.getStringList(kanaFavoritesKey) ?? [];
  for (final card in allKanaCards) {
    card.isFavorite = saved.contains(card.kana);
  }
}

Future<void> saveKanaFavorites() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.setStringList(
    kanaFavoritesKey,
    favoriteKanaCards.map((card) => card.kana).toList(),
  );
}
